In [1]:
import pandas as pd
import matplotlib
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [2]:
df_immoscout = pd.read_csv('wohnen_bern_agglo.csv')

In [3]:
df_immoscout.head(10)

objekt_id kategorie            objekt_strasse     objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
0    1108404   Wohnung  Oberfeld, Jurablickweg 7  Ostermundigen  3072     3.5         76.0      1680.0        240.0       1920.0
1    2034884   Wohnung           Freiestrasse 35           Bern  3012     2.5         45.0      1110.0        170.0       1280.0
2    3255700   Wohnung           Gerbestrasse 11  Ostermundigen  3072     3.0          NaN      1100.0        150.0       1250.0
3    3563474   Wohnung             Brunngasse 48           Bern  3011     1.5         42.0      1080.0        190.0       1270.0
4    3852208   Wohnung         Murtenstrasse 256           Bern  3027     2.5         55.0      1110.0        150.0       1260.0
5    3911925   Wohnung         Melchiorstrasse 7           Bern  3027     4.5          NaN      1698.0        270.0       1968.0
6    4941186   Wohnung             Bachstrasse 6  Ostermundigen  3072     2.5         51.0      1110.0        180.0       1290.0
7    4941976   Wohnung            Depotstrasse 2           Bern  3012     2.5         80.0      1720.0        150.0       1870.0
8    5085000   Wohnung         Grabenpromenade 5           Bern  3011     3.5         88.0      1805.0        230.0       2035.0
9    5293494   Wohnung   Ostermundigenstrasse 40           Bern  3006     4.0         90.0      1430.0        290.0       1720.0

In [4]:
# Wie viele Wohnungen insgesamt?
df_immoscout.shape

(1008, 10)

In [5]:
df_immoscout.dtypes

objekt_id           int64
kategorie          object
objekt_strasse     object
objekt_ort         object
plz                 int64
zimmer            float64
nutzflaeche       float64
nettomiete        float64
nebenkosten       float64
bruttomiete       float64
dtype: object

In [6]:
#Wie viele Wohnungen wo?
df_immoscout.objekt_ort.value_counts().head(10)

Bern                 523
Ostermundigen        108
Ittigen               54
Gümligen              40
Wabern                40
Liebefeld             37
Muri b. Bern          28
Schliern b. Köniz     27
Kehrsatz              23
Köniz                 23
Name: objekt_ort, dtype: int64

In [7]:
#Missing data bruttomiete
df_immoscout[df_immoscout.bruttomiete.isnull()] 

objekt_id kategorie          objekt_strasse       objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
11     5368777   Wohnung      Schänzlistrasse 19             Bern  3013     2.0          NaN         NaN          NaN          NaN
119    6203153   Wohnung            Junkerngasse             Bern  3011     4.0        260.0         NaN          NaN          NaN
140    6313358   Wohnung       Murtenstrasse 147             Bern  3008     NaN          NaN         NaN          NaN          NaN
207    6327910      Haus      Feldrainstrasse 61        Liebefeld  3097     7.5        240.0      4800.0          NaN          NaN
237    6360755   Wohnung                     NaN  Spiegel b. Bern  3095     3.0         75.0      3450.0          NaN          NaN
410    6289298   Wohnung       Vordere Länggasse             Bern  3012     4.0          NaN      2900.0        360.0          NaN
485    6269292      Haus     Bottigenstrasse 376             Bern  3020     5.5        220.0      3200.0          NaN          NaN
626    6363013   Wohnung          Ringstrasse 25    Ostermundigen  3072     3.5         58.0         NaN          NaN          NaN
659    6359144   Wohnung   Kirchenfeldstrasse 74             Bern  3005     NaN         60.0      2000.0          NaN          NaN
769    6338480   Wohnung                Talweg 2          Ittigen  3063     3.5         70.0         NaN          NaN          NaN
785    6345269   Wohnung               Talweg 15          Ittigen  3063     3.5        139.0         NaN          NaN          NaN
817    6359251   Wohnung     Mattenhofstrasse 20             Bern  3007     2.5          NaN         NaN          NaN          NaN
908    6357953   Wohnung  Wankdorffeldstrasse 77             Bern  3014     3.5        104.0      1950.0        350.0          NaN
909    6357954   Wohnung                     NaN             Bern  3014     3.5        104.0      1950.0        350.0          NaN
968    6349145   Wohnung         Chrottegässli 2         Bolligen  3065     1.0          NaN         NaN          NaN          NaN

In [8]:
df_immoscout[df_immoscout.bruttomiete.isnull()].shape

(15, 10)

In [9]:
df_immoscout.groupby('objekt_ort').kategorie.count().sort_values(ascending=False).head(10)

objekt_ort
Bern                 523
Ostermundigen        108
Ittigen               54
Gümligen              40
Wabern                40
Liebefeld             37
Muri b. Bern          28
Schliern b. Köniz     27
Bolligen              23
Köniz                 23
Name: kategorie, dtype: int64

## Nur Wohnungen in Bern

In [10]:
df_immoscout[df_immoscout.objekt_ort == 'Bern']

objekt_id kategorie               objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
1       2034884   Wohnung              Freiestrasse 35       Bern  3012     2.5         45.0      1110.0        170.0       1280.0
3       3563474   Wohnung                Brunngasse 48       Bern  3011     1.5         42.0      1080.0        190.0       1270.0
4       3852208   Wohnung            Murtenstrasse 256       Bern  3027     2.5         55.0      1110.0        150.0       1260.0
5       3911925   Wohnung            Melchiorstrasse 7       Bern  3027     4.5          NaN      1698.0        270.0       1968.0
7       4941976   Wohnung               Depotstrasse 2       Bern  3012     2.5         80.0      1720.0        150.0       1870.0
8       5085000   Wohnung            Grabenpromenade 5       Bern  3011     3.5         88.0      1805.0        230.0       2035.0
9       5293494   Wohnung      Ostermundigenstrasse 40       Bern  3006     4.0         90.0      1430.0        290.0       1720.0
11      5368777   Wohnung           Schänzlistrasse 19       Bern  3013     2.0          NaN         NaN          NaN          NaN
13      5545111   Wohnung                Lerchenweg 37       Bern  3012     2.5         67.0      1530.0        150.0       1680.0
14      5705514   Wohnung          Altenbergstrasse 38       Bern  3013     2.0          NaN      1232.0        180.0       1412.0
15      5753532   Wohnung          Murtenstrasse 143 B       Bern  3008     2.0         43.0      1130.0        170.0       1300.0
16      5805446   Wohnung              Hostettlerweg 4       Bern  3006     2.5         66.0      1950.0        180.0       2130.0
19      6004664   Wohnung              Hostettlerweg 4       Bern  3006     3.5         98.0      2500.0        271.0       2771.0
21      6110498   Wohnung                Neuhausweg 21       Bern  3027     3.5          NaN      1450.0        255.0       1705.0
23      6122490   Wohnung                 Postgasse 44       Bern  3011     3.5        104.0      2470.0        250.0       2720.0
25      6148960   Wohnung              Bolligenstr.28a       Bern  3006     3.0         97.0      1660.0        230.0       1890.0
26      6173977   Wohnung          Murtenstrasse 143 B       Bern  3008     2.0         48.0      1250.0        170.0       1420.0
27      6176331   Wohnung                Neuhausweg 21       Bern  3027     3.0          NaN      1320.0        245.0       1565.0
29      6212726   Wohnung             Sonnenbergrain 4       Bern  3013     6.5        150.0      3800.0        450.0       4250.0
32      6255979   Wohnung            Sonnenbergrain 57       Bern  3013     5.5        135.0      3500.0        450.0       3950.0
33      6256527   Wohnung              Nydeggstalden 2       Bern  3011     2.0          NaN      2790.0        200.0       2990.0
35      6271320   Wohnung           Schänzlistrasse 65       Bern  3013     2.0         44.0      1390.0        180.0       1570.0
36      6272812   Wohnung            Waldheimstrasse 8       Bern  3012     3.0         57.0      1300.0        220.0       1520.0
37      6274407   Wohnung             Reiterstrasse 15       Bern  3013     2.0         45.0      1210.0        170.0       1380.0
38      6279375   Wohnung         Holenackerstrasse 11       Bern  3027     3.5         73.0      1330.0        260.0       1590.0
47      6301597   Wohnung            Aarbergergasse 57       Bern  3011     2.5         95.0      2050.0        250.0       2300.0
48      6304922   Wohnung                 Aehrenweg 27       Bern  3027     3.0          NaN      1100.0        190.0       1290.0
49      6307725   Wohnung                Brunngasse 30       Bern  3011     1.5          NaN      1820.0        170.0       1990.0
51      6328295   Wohnung           Länggassstrasse 32       Bern  3012     1.0         14.0       300.0         90.0        390.0
54      6331095   Wohnung                Neuengasse 36       Bern  3011     

In [11]:
df_bern = df_immoscout[df_immoscout.objekt_ort == 'Bern']
df_bern.head(10)

objekt_id kategorie           objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
1     2034884   Wohnung          Freiestrasse 35       Bern  3012     2.5         45.0      1110.0        170.0       1280.0
3     3563474   Wohnung            Brunngasse 48       Bern  3011     1.5         42.0      1080.0        190.0       1270.0
4     3852208   Wohnung        Murtenstrasse 256       Bern  3027     2.5         55.0      1110.0        150.0       1260.0
5     3911925   Wohnung        Melchiorstrasse 7       Bern  3027     4.5          NaN      1698.0        270.0       1968.0
7     4941976   Wohnung           Depotstrasse 2       Bern  3012     2.5         80.0      1720.0        150.0       1870.0
8     5085000   Wohnung        Grabenpromenade 5       Bern  3011     3.5         88.0      1805.0        230.0       2035.0
9     5293494   Wohnung  Ostermundigenstrasse 40       Bern  3006     4.0         90.0      1430.0        290.0       1720.0
11    5368777   Wohnung       Schänzlistrasse 19       Bern  3013     2.0          NaN         NaN          NaN          NaN
13    5545111   Wohnung            Lerchenweg 37       Bern  3012     2.5         67.0      1530.0        150.0       1680.0
14    5705514   Wohnung      Altenbergstrasse 38       Bern  3013     2.0          NaN      1232.0        180.0       1412.0

In [12]:
df_bern.shape

(523, 10)

In [13]:
#Anz Wohnungen mit unbekannter Bruttomiete
df_bern[df_bern.bruttomiete.isnull()] 

objekt_id kategorie          objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
11     5368777   Wohnung      Schänzlistrasse 19       Bern  3013     2.0          NaN         NaN          NaN          NaN
119    6203153   Wohnung            Junkerngasse       Bern  3011     4.0        260.0         NaN          NaN          NaN
140    6313358   Wohnung       Murtenstrasse 147       Bern  3008     NaN          NaN         NaN          NaN          NaN
410    6289298   Wohnung       Vordere Länggasse       Bern  3012     4.0          NaN      2900.0        360.0          NaN
485    6269292      Haus     Bottigenstrasse 376       Bern  3020     5.5        220.0      3200.0          NaN          NaN
659    6359144   Wohnung   Kirchenfeldstrasse 74       Bern  3005     NaN         60.0      2000.0          NaN          NaN
817    6359251   Wohnung     Mattenhofstrasse 20       Bern  3007     2.5          NaN         NaN          NaN          NaN
908    6357953   Wohnung  Wankdorffeldstrasse 77       Bern  3014     3.5        104.0      1950.0        350.0          NaN
909    6357954   Wohnung                     NaN       Bern  3014     3.5        104.0      1950.0        350.0          NaN

In [14]:
#Um Verzerrungen bei den Durchschnittsmieten zu vermeiden, droppen wir die Wohnungen mit unbekannter Bruttomiete
df_bern.dropna(subset=['bruttomiete'])

objekt_id kategorie               objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
1       2034884   Wohnung              Freiestrasse 35       Bern  3012     2.5         45.0      1110.0        170.0       1280.0
3       3563474   Wohnung                Brunngasse 48       Bern  3011     1.5         42.0      1080.0        190.0       1270.0
4       3852208   Wohnung            Murtenstrasse 256       Bern  3027     2.5         55.0      1110.0        150.0       1260.0
5       3911925   Wohnung            Melchiorstrasse 7       Bern  3027     4.5          NaN      1698.0        270.0       1968.0
7       4941976   Wohnung               Depotstrasse 2       Bern  3012     2.5         80.0      1720.0        150.0       1870.0
8       5085000   Wohnung            Grabenpromenade 5       Bern  3011     3.5         88.0      1805.0        230.0       2035.0
9       5293494   Wohnung      Ostermundigenstrasse 40       Bern  3006     4.0         90.0      1430.0        290.0       1720.0
13      5545111   Wohnung                Lerchenweg 37       Bern  3012     2.5         67.0      1530.0        150.0       1680.0
14      5705514   Wohnung          Altenbergstrasse 38       Bern  3013     2.0          NaN      1232.0        180.0       1412.0
15      5753532   Wohnung          Murtenstrasse 143 B       Bern  3008     2.0         43.0      1130.0        170.0       1300.0
16      5805446   Wohnung              Hostettlerweg 4       Bern  3006     2.5         66.0      1950.0        180.0       2130.0
19      6004664   Wohnung              Hostettlerweg 4       Bern  3006     3.5         98.0      2500.0        271.0       2771.0
21      6110498   Wohnung                Neuhausweg 21       Bern  3027     3.5          NaN      1450.0        255.0       1705.0
23      6122490   Wohnung                 Postgasse 44       Bern  3011     3.5        104.0      2470.0        250.0       2720.0
25      6148960   Wohnung              Bolligenstr.28a       Bern  3006     3.0         97.0      1660.0        230.0       1890.0
26      6173977   Wohnung          Murtenstrasse 143 B       Bern  3008     2.0         48.0      1250.0        170.0       1420.0
27      6176331   Wohnung                Neuhausweg 21       Bern  3027     3.0          NaN      1320.0        245.0       1565.0
29      6212726   Wohnung             Sonnenbergrain 4       Bern  3013     6.5        150.0      3800.0        450.0       4250.0
32      6255979   Wohnung            Sonnenbergrain 57       Bern  3013     5.5        135.0      3500.0        450.0       3950.0
33      6256527   Wohnung              Nydeggstalden 2       Bern  3011     2.0          NaN      2790.0        200.0       2990.0
35      6271320   Wohnung           Schänzlistrasse 65       Bern  3013     2.0         44.0      1390.0        180.0       1570.0
36      6272812   Wohnung            Waldheimstrasse 8       Bern  3012     3.0         57.0      1300.0        220.0       1520.0
37      6274407   Wohnung             Reiterstrasse 15       Bern  3013     2.0         45.0      1210.0        170.0       1380.0
38      6279375   Wohnung         Holenackerstrasse 11       Bern  3027     3.5         73.0      1330.0        260.0       1590.0
47      6301597   Wohnung            Aarbergergasse 57       Bern  3011     2.5         95.0      2050.0        250.0       2300.0
48      6304922   Wohnung                 Aehrenweg 27       Bern  3027     3.0          NaN      1100.0        190.0       1290.0
49      6307725   Wohnung                Brunngasse 30       Bern  3011     1.5          NaN      1820.0        170.0       1990.0
51      6328295   Wohnung           Länggassstrasse 32       Bern  3012     1.0         14.0       300.0         90.0        390.0
54      6331095   Wohnung                Neuengasse 36       Bern  3011     3.5        120.0      2400.0        150.0       2550.0
55      6335737   Wohnung               Radarstrasse 1       Bern  3013     

In [15]:
#Neue Datenbank enthält 514 Wohnungen in Bern mit Angaben zur Bruttomiete
df_bern = df_bern.dropna(subset=['bruttomiete'])
df_bern.shape

(514, 10)

# Wohnungen in Bern nach Grösse und Miete
- Wie viele Wohnungen sind in Bern total auf dem Markt (nach Immoscout)?
- Wie hoch ist die durchschnittliche Miete in Bern für 3.5- und 4.5-Zimmerwohnung?

In [16]:
#Insgesamt in Bern
df_bern.zimmer.value_counts(ascending=False).head(15)

3.5    110
2.5    101
3.0     83
2.0     76
1.0     51
4.5     40
1.5     19
4.0     14
5.0      6
5.5      6
6.0      1
7.5      1
6.5      1
Name: zimmer, dtype: int64

In [17]:
#3.5-Zimmer-Wohnungen in Bern
dreieinhalbzimmer_bern = df_bern[df_bern.zimmer == 3.5]
dreieinhalbzimmer_bern.head(5)

objekt_id kategorie        objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
8     5085000   Wohnung     Grabenpromenade 5       Bern  3011     3.5         88.0      1805.0        230.0       2035.0
19    6004664   Wohnung       Hostettlerweg 4       Bern  3006     3.5         98.0      2500.0        271.0       2771.0
21    6110498   Wohnung         Neuhausweg 21       Bern  3027     3.5          NaN      1450.0        255.0       1705.0
23    6122490   Wohnung          Postgasse 44       Bern  3011     3.5        104.0      2470.0        250.0       2720.0
38    6279375   Wohnung  Holenackerstrasse 11       Bern  3027     3.5         73.0      1330.0        260.0       1590.0

In [18]:
#Durchschnittsmiete 3.5-Z in Bern:
dreieinhalbzimmer_bern.bruttomiete.median()

1750.0

In [19]:
#Total 4.5-Zimmer-Wohnungen in Bern
viereinhalbzimmer_bern = df_bern[df_bern.zimmer == 4.5]
viereinhalbzimmer_bern.head(5)

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
5      3911925   Wohnung   Melchiorstrasse 7       Bern  3027     4.5          NaN      1698.0        270.0       1968.0
56     6335742   Wohnung      Radarstrasse 1       Bern  3013     4.5         86.0      1850.0        400.0       2250.0
81     2344777   Wohnung          Billeweg 6       Bern  3027     4.5        100.0      1980.0        280.0       2260.0
91     5632652   Wohnung                 NaN       Bern  3011     4.5        111.0      2570.0        250.0       2820.0
131    6292011   Wohnung  Riedbachstrasse 76       Bern  3027     4.5        112.0      2180.0        400.0       2580.0

In [20]:
#Durchschnittsmiete 4.5-Z in Bern:
viereinhalbzimmer_bern.bruttomiete.median()

2567.5

# Wohnungen nach Grösse und Quartier
- 3013: Altenberg, Breitenrain, Lorraine, Spitalacker
- 3027: Bethlehem 
- 3014: Beundenfeld, Breitfeld
- 3006: Brunnadern, Gryphenhübeli, Schosshalde
- 3018: Bümpliz, Stöckacker
- 3012: Engeried, Länggasse, Muesmatt, Neufeld, Stadtbach
- 3004: Felsenau
- 3011: Innenstadt (Gelbes Quartier, Grünes Quartier, Rotes Quartier, Mattequartier, Weisses Quartier)
- 3008: Holligen, Weissenstein
- 3005: Kirchenfeld
- 3007: Mattenhof, Monbijou, Sandrain, Weissenbühl
- 3015: Murifeld
- 3019: Oberbottigen

## 1. Ergebnisse für Breitenrain-Lorraine (3013)
#### Erkenntnis: Wenig Wohnungen auf dem Markt, am meisten kleine (2-Zimmerwohnungen, 9)
- Total ausgeschriebene Wohnungen: 34 
- Durchschnittsmiete (Brutto) 3.5-Zimmerwohnung: 2085 CHF 
- Durchschnittsmiete 4.5-Zimmerwohnung: 2565 CHF

In [21]:
#Name für Quartiere 3013: Zur Vereinfachung "Breitenrain-Lorraine" genannt
breitenrain_lorraine = df_bern[df_bern.plz == 3013]
breitenrain_lorraine.head()

objekt_id kategorie       objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
14    5705514   Wohnung  Altenbergstrasse 38       Bern  3013     2.0          NaN      1232.0        180.0       1412.0
29    6212726   Wohnung     Sonnenbergrain 4       Bern  3013     6.5        150.0      3800.0        450.0       4250.0
32    6255979   Wohnung    Sonnenbergrain 57       Bern  3013     5.5        135.0      3500.0        450.0       3950.0
35    6271320   Wohnung   Schänzlistrasse 65       Bern  3013     2.0         44.0      1390.0        180.0       1570.0
37    6274407   Wohnung     Reiterstrasse 15       Bern  3013     2.0         45.0      1210.0        170.0       1380.0

In [22]:
#Wohnungen total in 3013 (Breitenrain-Lorraine)
breitenrain_lorraine.zimmer.value_counts(ascending=False).head(15)

2.0    9
3.5    6
2.5    5
1.0    4
3.0    3
4.5    3
1.5    1
5.0    1
5.5    1
6.5    1
Name: zimmer, dtype: int64

In [23]:
#Total Wohnungen in 3013 (Breitenrain-Lorraine)
breitenrain_lorraine.shape

(34, 10)

In [24]:
#3.5-Zimmer-Wohnungen in Breitenrain-Lorraine
dreieinhalbzimmer_breitsch = breitenrain_lorraine[breitenrain_lorraine.zimmer == 3.5]
dreieinhalbzimmer_breitsch.head(5)

objekt_id kategorie     objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
55     6335737   Wohnung     Radarstrasse 1       Bern  3013     3.5         80.0      1750.0        350.0       2100.0
383    5879097   Wohnung         Nordweg 10       Bern  3013     3.5         85.0      2420.0        280.0       2700.0
384    5902951   Wohnung  Greyerzstrasse 19       Bern  3013     3.5         81.0      2240.0        250.0       2490.0
405    6215678   Wohnung      Centralweg 16       Bern  3013     3.5        110.0      1800.0        270.0       2070.0
590    6337338   Wohnung         Randweg 17       Bern  3013     3.5         85.0      1460.0        230.0       1690.0

In [25]:
#Durchschnittsmiete 3.5-Z in 3013 (Breitenrain-Lorraine):
dreieinhalbzimmer_breitsch.bruttomiete.median()

2085.0

In [26]:
#4.5-Zimmer-Wohnungen in 3013 (Breitenrain-Lorraine)
viereinhalbzimmer_breitsch = breitenrain_lorraine[breitenrain_lorraine.zimmer == 4.5]
viereinhalbzimmer_breitsch.head(5)

objekt_id kategorie         objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
56     6335742   Wohnung         Radarstrasse 1       Bern  3013     4.5         86.0      1850.0        400.0       2250.0
429    6320020   Wohnung  Spitalackerstrasse 51       Bern  3013     4.5         94.0      2300.0        265.0       2565.0
591    6338803   Wohnung  Breitenrainstrasse 11       Bern  3013     4.5          NaN      2790.0        305.0       3095.0

In [27]:
#Durchschnittsmiete 4.5-Z in 3013 (Breitenrain-Lorraine):
viereinhalbzimmer_breitsch.bruttomiete.median()

2565.0

## 2. Ergebnisse für Bethlehem (3027)
#### Erkenntnis: Der Preis für eine 4.5-Zimmerwohnung ist mit 2389 CHF wider Erwarten hoch. Vermutung: Hat mit der Neubautätigkeit rund ums Westside zu tun (Neubaustandard).
- Total freie Wohnungen: 37 
- Durchschnittsmiete 3.5-Zimmerwohnung:1754.50 CHF
- Durchschnittsmiete 4.5-Zimmerwohnung: 2389 CHF

In [28]:
#Bethlehem
bethlehem = df_bern[df_bern.plz == 3027]
bethlehem.head()

objekt_id kategorie        objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
4     3852208   Wohnung     Murtenstrasse 256       Bern  3027     2.5         55.0      1110.0        150.0       1260.0
5     3911925   Wohnung     Melchiorstrasse 7       Bern  3027     4.5          NaN      1698.0        270.0       1968.0
21    6110498   Wohnung         Neuhausweg 21       Bern  3027     3.5          NaN      1450.0        255.0       1705.0
27    6176331   Wohnung         Neuhausweg 21       Bern  3027     3.0          NaN      1320.0        245.0       1565.0
38    6279375   Wohnung  Holenackerstrasse 11       Bern  3027     3.5         73.0      1330.0        260.0       1590.0

In [29]:
#Total Wohnungen in Bethlehem
bethlehem.zimmer.value_counts(ascending=False).head(10)

3.5    18
3.0     7
4.5     4
2.5     4
2.0     1
1.0     1
4.0     1
Name: zimmer, dtype: int64

In [30]:
bethlehem.shape

(37, 10)

In [31]:
#3.5-Zimmer-Wohnungen in Bethlehem
dreieinhalbzimmer_bethlehem = bethlehem[bethlehem.zimmer == 3.5]
dreieinhalbzimmer_bethlehem.head(5)

objekt_id kategorie        objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
21     6110498   Wohnung         Neuhausweg 21       Bern  3027     3.5          NaN      1450.0        255.0       1705.0
38     6279375   Wohnung  Holenackerstrasse 11       Bern  3027     3.5         73.0      1330.0        260.0       1590.0
80     2182194   Wohnung        Zelgstrasse 14       Bern  3027     3.5         86.0      1220.0        180.0       1400.0
95     5754947   Wohnung    Waldmannstrasse 14       Bern  3027     3.5          NaN      1300.0        250.0       1550.0
104    5973696   Wohnung    Riedbachstrasse 65       Bern  3027     3.5          NaN      1625.0        220.0       1845.0

In [32]:
#Durchschnittsmiete 3.5-Z in Bethlehem:
dreieinhalbzimmer_bethlehem.bruttomiete.median()

1754.5

In [33]:
#4.5-Zimmer-Wohnungen in Bethlehem:
viereinhalbzimmer_bethlehem = bethlehem[bethlehem.zimmer == 4.5]
viereinhalbzimmer_bethlehem.head(5)

objekt_id kategorie               objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
5      3911925   Wohnung            Melchiorstrasse 7       Bern  3027     4.5          NaN      1698.0        270.0       1968.0
81     2344777   Wohnung                   Billeweg 6       Bern  3027     4.5        100.0      1980.0        280.0       2260.0
131    6292011   Wohnung           Riedbachstrasse 76       Bern  3027     4.5        112.0      2180.0        400.0       2580.0
280    6352195   Wohnung  OpenCourts - OC Gigonweg 10       Bern  3027     4.5        108.0      2140.0        360.0       2500.0

In [34]:
#Durchschnittsmiete 4.5-Z in Bethlehem:
viereinhalbzimmer_bethlehem.bruttomiete.median()

2380.0

## 3. Ergebnisse für Beundenfeld/Breitfeld (3014)
#### Erkenntnis: Auch hier deutlich am meisten kleine Wohnungen auf dem Markt: nämlich 2.5-Zi (12) und 1-Zi (8).
- Total freie Wohnungen: 48
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 1740
- Durchschnittsmiete 4.5-Zimmerwohnung: CHF 2300 

In [35]:
#Beundenfeld/Breitfeld
beundenfeld_breitfeld = df_bern[df_bern.plz == 3014]
beundenfeld_breitfeld.head()

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
534    5850512   Wohnung   Hilfikerstrasse 2       Bern  3014     5.0         85.0      2994.0        256.0       3250.0
538    5972897   Wohnung   Hilfikerstrasse 4       Bern  3014     2.5         55.0      1590.0        160.0       1750.0
606    6350174   Wohnung    Allmendstrasse 5       Bern  3014     2.5        100.0      2100.0        270.0       2370.0
837    1745328   Wohnung           Zielweg 5       Bern  3014     2.5         60.0      1300.0        250.0       1550.0
839    3707844   Wohnung  Scheibenstrasse 47       Bern  3014     1.0          NaN       960.0        100.0       1060.0

In [36]:
#Total Wohnungen in BB
beundenfeld_breitfeld.zimmer.value_counts(ascending=False).head(10)

2.5    12
1.0     8
3.0     7
2.0     6
3.5     6
1.5     3
4.5     3
6.0     1
4.0     1
5.0     1
Name: zimmer, dtype: int64

In [37]:
beundenfeld_breitfeld.shape

(48, 10)

In [38]:
#3.5-Zimmer-Wohnungen in BB
dreieinhalbzimmer_bb = beundenfeld_breitfeld[beundenfeld_breitfeld.zimmer == 3.5]
dreieinhalbzimmer_bb.head(5)

objekt_id kategorie          objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
844    5692901   Wohnung        Wylerstrasse 109       Bern  3014     3.5          NaN      2100.0        400.0       2500.0
876    6313138   Wohnung  Attinghausenstrasse 26       Bern  3014     3.5          NaN      1720.0        200.0       1920.0
888    6336552   Wohnung        Wiesenstrasse 83       Bern  3014     3.5        103.0      2300.0        310.0       2610.0
895    6352860   Wohnung          Flurstrasse 24       Bern  3014     3.5         70.0      1400.0        150.0       1550.0
897    6353562   Wohnung       Winkelriedstr. 13       Bern  3014     3.5         66.0      1310.0        195.0       1505.0

In [39]:
#Durchschnittsmiete 3.5-Z in BB:
dreieinhalbzimmer_bb.bruttomiete.median()

1740.0

In [40]:
#4.5-Zimmer-Wohnungen in BB
viereinhalbzimmer_bb = beundenfeld_breitfeld[beundenfeld_breitfeld.zimmer == 4.5]
viereinhalbzimmer_bb.head(5)

objekt_id kategorie          objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
843    5247303   Wohnung    Winkelriedstrasse 28       Bern  3014     4.5          NaN      1420.0        230.0       1650.0
883    6333417   Wohnung  Wankdorffeldstrasse 73       Bern  3014     4.5        120.0         NaN          NaN       2300.0
921    6364098   Wohnung   Elisabethenstrasse 21       Bern  3014     4.5          NaN      3050.0        360.0       3410.0

In [41]:
viereinhalbzimmer_bb.bruttomiete.median()

2300.0

## 4. Ergebnisse für 3006: Brunnadern, Gryphenhübeli, Schosshalde
#### Erkenntnis: in Brunnadern, Gryphenhübeli und Schosshalde dominieren die kleineren Wohnungen wie 2-Zi (17) und 3-Zi (16)
- Total freie Wohnungen: 87
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 1900
- Durchschnittsmiete 4.5-Zimmerwohnung: CHF 2701 

In [42]:
#Brunnadern/Gryphenhübeli/Schosshalde (bgs)
bgs = df_bern[df_bern.plz == 3006]
bgs.head()

objekt_id kategorie           objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
9     5293494   Wohnung  Ostermundigenstrasse 40       Bern  3006     4.0         90.0      1430.0        290.0       1720.0
16    5805446   Wohnung          Hostettlerweg 4       Bern  3006     2.5         66.0      1950.0        180.0       2130.0
19    6004664   Wohnung          Hostettlerweg 4       Bern  3006     3.5         98.0      2500.0        271.0       2771.0
25    6148960   Wohnung          Bolligenstr.28a       Bern  3006     3.0         97.0      1660.0        230.0       1890.0
68    6353546   Wohnung           Bolligenstr.28       Bern  3006     5.5        146.0      2540.0        460.0       3000.0

In [43]:
# Total freie Wohnungen bgs
bgs.zimmer.value_counts(ascending=False).head(10)

2.0    17
3.0    16
3.5    15
2.5    11
4.5    10
1.0     8
4.0     4
1.5     2
5.5     2
5.0     1
Name: zimmer, dtype: int64

In [44]:
bgs.shape

(87, 10)

In [45]:
#3.5-Zimmer-Wohnungen in bgs
dreieinhalbzimmer_bgs = bgs[bgs.zimmer == 3.5]
dreieinhalbzimmer_bgs.head(5)

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
19     6004664   Wohnung     Hostettlerweg 4       Bern  3006     3.5         98.0      2500.0        271.0       2771.0
73     6357484   Wohnung   Bitziusstrasse 40       Bern  3006     3.5         88.0      2250.0        240.0       2490.0
297    6360862   Wohnung     Weltistrasse 56       Bern  3006     3.5        110.0      2300.0        460.0       2760.0
306    6364138   Wohnung  Bantigerstrasse 37       Bern  3006     3.5          NaN      2690.0        230.0       2920.0
307    6364742   Wohnung     Weltistrasse 32       Bern  3006     3.5         88.0      1380.0        250.0       1630.0

In [46]:
# Durchschnittsmiete 3.5 Zi-Wohnung in bgs
dreieinhalbzimmer_bgs.bruttomiete.median()

1900.0

In [47]:
#4.5-Zimmer-Wohnungen in bgs
viereinhalbzimmer_bgs = bgs[bgs.zimmer == 4.5]
viereinhalbzimmer_bgs.head(5)

objekt_id kategorie          objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
402    6194115   Wohnung              Zentweg 21       Bern  3006     4.5        307.0      4685.0        539.0       5224.0
448    5135886   Wohnung  Schildknechtstrasse 30       Bern  3006     4.5          NaN      2400.0        350.0       2750.0
457    6048186   Wohnung          Muristrasse 61       Bern  3006     4.5          NaN      1920.0        285.0       2205.0
528    5661845   Wohnung                     NaN       Bern  3006     4.5        130.0      1800.0          NaN       1800.0
531    5793096   Wohnung       Seminarstrasse 11       Bern  3006     4.5        110.0      2500.0        300.0       2800.0

In [48]:
#Durchschnittsmiete 4.5 Zimmer-Wohnung in bgs
viereinhalbzimmer_bgs.bruttomiete.median()

2701.0

## 5. Ergebnisse für: 3018: Bümpliz, Stöckacker
#### Erkenntnis: In Bümpliz und Stöckacker dominieren die 3.5-Zi (26) und 3-Zi-Wohnungen (15). 
- Im Total 71 Wohnungen verfügbar
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 1595 
- Durchschnittsmiete 4.5-Zimmerwohnung: CHF 2190 (nur eine Wohnung ausgeschrieben) 

In [49]:
#Bümpliz/Stöckacker
buempliz = df_bern[df_bern.plz == 3018]
buempliz.head()

objekt_id kategorie       objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
85     4379560   Wohnung     Keltenstrasse 35       Bern  3018     3.5          NaN      1190.0        240.0       1430.0
90     5547702   Wohnung  Mühledorfstrasse 21       Bern  3018     3.5         69.0      1520.0        170.0       1690.0
100    5889857   Wohnung   Brünnenstrasse 43a       Bern  3018     2.5         54.0      1415.0        130.0       1545.0
122    6212381   Wohnung    Bümplizstrasse 69       Bern  3018     1.0         43.0      1060.0        140.0       1200.0
125    6236126   Wohnung  Mühledorfstrasse 20       Bern  3018     4.0          NaN      1500.0        250.0       1750.0

In [50]:
# Total freie Wohnungen Bümpliz
buempliz.zimmer.value_counts(ascending=False).head(10)

3.5    26
3.0    15
2.5    13
1.0     7
1.5     3
2.0     2
5.0     2
4.0     2
4.5     1
Name: zimmer, dtype: int64

In [51]:
buempliz.shape

(71, 10)

In [52]:
#3.5-Zimmer-Wohnungen in Bümpliz
dreieinhalbzimmer_buempliz = buempliz[buempliz.zimmer == 3.5]
dreieinhalbzimmer_buempliz.head(5)

objekt_id kategorie       objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
85     4379560   Wohnung     Keltenstrasse 35       Bern  3018     3.5          NaN      1190.0        240.0       1430.0
90     5547702   Wohnung  Mühledorfstrasse 21       Bern  3018     3.5         69.0      1520.0        170.0       1690.0
252    6332716   Wohnung     Bethlehemstr. 70       Bern  3018     3.5          NaN      1195.0        275.0       1470.0
299    6361371   Wohnung  Normannenstrasse 35       Bern  3018     3.5         75.0      1275.0        220.0       1495.0
478    6230593   Wohnung       Heimstrasse 71       Bern  3018     3.5          NaN      1580.0        390.0       1970.0

In [53]:
#Durchschnittsmiete 3.5-Zimmerwohnung Bümpliz
dreieinhalbzimmer_buempliz.bruttomiete.median()

1595.0

In [54]:
#Durchschnittsmiete 4.5-Zimmerwohnung Bümpliz ACHTUNG!!! Nur eine Wohnung ausgeschrieben
viereinhalbzimmer_buempliz = buempliz[buempliz.zimmer == 4.5]
viereinhalbzimmer_buempliz.head(5)

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
133    6300532   Wohnung  Mühledorfstrasse 1       Bern  3018     4.5        100.0         NaN          NaN       2190.0

## 6. Ergebnisse für 3012: Engeried, Länggasse, Muesmatt, Neufeld, Stadtbach
#### Erkenntnis: In 3012 (Uni-Quartier) hat es keine einzige 4.5-Zimmerwohnung ausgeschrieben. Es dominieren auch hier 1-Zi (8), 2-  und 2.5-Zi (5) und 3-Zi (5). Achtung: Generell wenige Wohnungen ausgeschrieben.
- Total freie Wohnungen: 29 
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 2338.50 
- Durchschnittsmiete 4.5-Zimmerwohnung: Keine frei 

In [55]:
#Engeried, Länggasse, Muesmatt, Neufeld, Stadtbach, genannt: laenggasse
laenggasse = df_bern[df_bern.plz == 3012]
laenggasse.head()

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
1     2034884   Wohnung     Freiestrasse 35       Bern  3012     2.5         45.0      1110.0        170.0       1280.0
7     4941976   Wohnung      Depotstrasse 2       Bern  3012     2.5         80.0      1720.0        150.0       1870.0
13    5545111   Wohnung       Lerchenweg 37       Bern  3012     2.5         67.0      1530.0        150.0       1680.0
36    6272812   Wohnung   Waldheimstrasse 8       Bern  3012     3.0         57.0      1300.0        220.0       1520.0
51    6328295   Wohnung  Länggassstrasse 32       Bern  3012     1.0         14.0       300.0         90.0        390.0

In [56]:
# Total freie Wohnungen laenggasse
laenggasse.zimmer.value_counts(ascending=False)

1.0    8
2.0    5
3.0    5
2.5    5
3.5    4
4.0    1
Name: zimmer, dtype: int64

In [57]:
laenggasse.shape

(29, 10)

In [58]:
#3.5-Zimmer-Wohnungen in laenggasse
dreieinhalbzimmer_laenggasse = laenggasse[laenggasse.zimmer == 3.5]
dreieinhalbzimmer_laenggasse.head(5)

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
66     6350645   Wohnung  Waldheimstrasse 31       Bern  3012     3.5         72.0      2100.0        250.0       2350.0
374    3829729   Wohnung                 NaN       Bern  3012     3.5        130.0      2550.0        450.0       3000.0
602    6348901   Wohnung                 NaN       Bern  3012     3.5          NaN      2150.0          NaN       2150.0
898    6353905   Wohnung   Diesbachstrasse 1       Bern  3012     3.5        114.0       390.0       1937.0       2327.0

In [59]:
#Durchschnittsmiete 3.5-Zimmerwohnung laenggasse
dreieinhalbzimmer_laenggasse.bruttomiete.median()

2338.5

## 7. Ergebnisse für 3004: Felsenau
#### Erkenntnis: 3- und 3.5-Zi-Wohnungen überwiegen (je 5). Darüber hinaus keine grösseren Wohnungen frei, generell wenige inseriert (15).
- Total freie Wohnungen: 15  
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 1900
- Durchschnittsmiete 4.5-Zimmerwohnung: Keine frei

In [60]:
#felsenau
felsenau = df_bern[df_bern.plz == 3004]
felsenau.head()

objekt_id kategorie         objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
521    5232552   Wohnung       Felshaldenweg 23       Bern  3004     2.0          NaN      1220.0        170.0       1390.0
537    5971909   Wohnung       Felshaldenweg 33       Bern  3004     2.5          NaN      1100.0        110.0       1210.0
547    6078658   Wohnung  Reichenbachstrasse 11       Bern  3004     3.5         62.0      1280.0        210.0       1490.0
738    6296106   Wohnung    Tiefenaustrasse 141       Bern  3004     3.0         62.0      1465.0        190.0       1655.0
739    6302968   Wohnung    Tiefenaustrasse 135       Bern  3004     3.0          NaN      1290.0        200.0       1490.0

In [61]:
#Total freie Wohnungen felsenau
felsenau.shape

(15, 10)

In [62]:
#Was?
felsenau.zimmer.value_counts(ascending=False)

3.0    5
3.5    5
2.5    2
2.0    2
1.5    1
Name: zimmer, dtype: int64

In [63]:
#3.5-Zimmer-Wohnungen in der felsenau
dreieinhalbzimmer_felsenau = felsenau[felsenau.zimmer == 3.5]
dreieinhalbzimmer_felsenau.head(5)

objekt_id kategorie               objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
547    6078658   Wohnung        Reichenbachstrasse 11       Bern  3004     3.5         62.0      1280.0        210.0       1490.0
751    6325494   Wohnung       Reichenbachstrasse 87A       Bern  3004     3.5        105.0      1950.0        350.0       2300.0
771    6339475   Wohnung  Hintere Engehaldestrasse 12       Bern  3004     3.5         86.0      1550.0        250.0       1800.0
830    6363043   Wohnung  Hintere Engehaldestrasse 12       Bern  3004     3.5        107.0      1650.0        250.0       1900.0
831    6363180   Wohnung        Engehaldestrasse 198A       Bern  3004     3.5         95.0      2850.0        350.0       3200.0

In [64]:
#Bruttomiete 3.5-Zimmerwohnung Felsenau
dreieinhalbzimmer_felsenau.bruttomiete.median()

1900.0

## 8. Ergebnisse für 3011: Innenstadt (Gelbes Quartier, Grünes Quartier, Rotes Quartier, Matte, Weisses Quartier)
#### Erkenntnis: Auch hier kaum grössere Wohnungen frei (nur 2 4.5-Zi, 1 x 5-Zi und 1x 5.5-Zi). Teuer!
- Total freie Wohnungen: 43
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 2550
- Durchschnittsmiete 4.5-Zimmerwohnung: CHF 3055

In [65]:
#innenstadt
innenstadt = df_bern[df_bern.plz == 3011]
innenstadt.head()

objekt_id kategorie     objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
3     3563474   Wohnung      Brunngasse 48       Bern  3011     1.5         42.0      1080.0        190.0       1270.0
8     5085000   Wohnung  Grabenpromenade 5       Bern  3011     3.5         88.0      1805.0        230.0       2035.0
23    6122490   Wohnung       Postgasse 44       Bern  3011     3.5        104.0      2470.0        250.0       2720.0
33    6256527   Wohnung    Nydeggstalden 2       Bern  3011     2.0          NaN      2790.0        200.0       2990.0
47    6301597   Wohnung  Aarbergergasse 57       Bern  3011     2.5         95.0      2050.0        250.0       2300.0

In [66]:
# Total freie Wohnungen innenstadt
innenstadt.zimmer.value_counts(ascending=False)

2.5    10
2.0     9
3.5     7
1.5     6
3.0     4
1.0     3
4.5     2
5.5     1
5.0     1
Name: zimmer, dtype: int64

In [67]:
innenstadt.shape

(43, 10)

In [68]:
#3.5-Zimmer-Wohnungen in der felsenau
dreieinhalbzimmer_innenstadt = innenstadt[innenstadt.zimmer == 3.5]
dreieinhalbzimmer_innenstadt.head(5)

objekt_id kategorie     objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
8      5085000   Wohnung  Grabenpromenade 5       Bern  3011     3.5         88.0      1805.0        230.0       2035.0
23     6122490   Wohnung       Postgasse 44       Bern  3011     3.5        104.0      2470.0        250.0       2720.0
54     6331095   Wohnung      Neuengasse 36       Bern  3011     3.5        120.0      2400.0        150.0       2550.0
97     5794257   Wohnung       Kramgasse 39       Bern  3011     3.5          NaN      2790.0        190.0       2980.0
106    6110536   Wohnung                NaN       Bern  3011     3.5        100.0      3960.0          NaN       3960.0

In [69]:
#Durchschnittsmiete 3.5-Zimmerwohnung innenstadt
dreieinhalbzimmer_innenstadt.bruttomiete.median()

2550.0

In [70]:
#4.5-Zimmer-Wohnungen in innenstadt
viereinhalbzimmer_innenstadt = innenstadt[innenstadt.zimmer == 4.5]
viereinhalbzimmer_innenstadt.head(5)

objekt_id kategorie objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
91     5632652   Wohnung            NaN       Bern  3011     4.5        111.0      2570.0        250.0       2820.0
289    6357095   Wohnung   Postgasse 60       Bern  3011     4.5        153.0      3000.0        290.0       3290.0

In [71]:
#Durchschnittsmiete 4.5 Zimmerwohnung in der Innenstadt (ACHTUNG: NUR 2 Wohnungen)
viereinhalbzimmer_innenstadt.bruttomiete.median()

3055.0

## 9. Ergebnisse für 3008: Holligen, Weissenstein
#### Erkenntnis: Erneut sind mit Abstand am meisten der inserierten Wohnungen 2.5-Zi (15) und 2 Zi (10). Familienwohnungen Fehlanzeige (gibt 4 4.5-Zimmerwohnungen).
- Total freie Wohnungen: 45 
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 1675 
- Durchschnittsmiete 4.5-Zimmerwohnung: CHF 2625 

In [72]:
#Holligen/Weissenstein
hol_ws = df_bern[df_bern.plz == 3008]
hol_ws.head()

objekt_id kategorie       objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
15    5753532   Wohnung  Murtenstrasse 143 B       Bern  3008     2.0         43.0      1130.0        170.0       1300.0
26    6173977   Wohnung  Murtenstrasse 143 B       Bern  3008     2.0         48.0      1250.0        170.0       1420.0
67    6352110   Wohnung  Murtenstrasse 143 B       Bern  3008     2.0         48.0      1230.0        170.0       1400.0
75    6359934   Wohnung  Murtenstrasse 143 B       Bern  3008     2.0         40.0      1080.0        170.0       1250.0
87    4781573   Wohnung   Freiburgstrasse 58       Bern  3008     2.0        109.0         NaN          NaN        760.0

In [73]:
#Total freie Wohnungen Holligen/Weissenstein
hol_ws.zimmer.value_counts(ascending=False).head(10)

2.5    15
2.0    10
3.5     7
4.5     4
1.0     4
3.0     3
1.5     1
Name: zimmer, dtype: int64

In [74]:
hol_ws.shape

(45, 10)

In [75]:
#3.5-Zimmer-Wohnungen Holligen/Weissenstein
dreieinhalbzimmer_hol_ws = hol_ws[hol_ws.zimmer == 3.5]
dreieinhalbzimmer_hol_ws.head(5)

objekt_id kategorie        objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
94     5726538   Wohnung      Schenkstrasse 37       Bern  3008     3.5         65.0      1340.0        210.0       1550.0
281    6352853   Wohnung    Freiburgstrasse 68       Bern  3008     3.5         80.0      1500.0        180.0       1680.0
291    6358723   Wohnung      Güterstrasse  44       Bern  3008     3.5         75.0         NaN          NaN       1690.0
548    6079458   Wohnung         Europaplatz 1       Bern  3008     3.5         91.0      2025.0        265.0       2290.0
565    6203601   Wohnung  Freiburgstrasse 123B       Bern  3008     3.5          NaN      1325.0        252.0       1577.0

In [76]:
#Durchschnittsmiete 3.5-Zimmerwohnung in Holligen/Weissenstein
dreieinhalbzimmer_hol_ws.bruttomiete.median()

1675.0

In [77]:
#4.5-Zimmer-Wohnungen in innenstadt
viereinhalbzimmer_hol_ws = hol_ws[hol_ws.zimmer == 4.5]
viereinhalbzimmer_hol_ws.head(5)

objekt_id kategorie           objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
138    6306244   Wohnung      Murtenstrasse 143 H       Bern  3008     4.5        123.0      2370.0        310.0       2680.0
143    6321329   Wohnung      Murtenstrasse 143 G       Bern  3008     4.5        123.0      2220.0        350.0       2570.0
264    6344269   Wohnung      Murtenstrasse 143 F       Bern  3008     4.5        105.0      2400.0        400.0       2800.0
936    6325127   Wohnung  Schwarzenburgstrasse 67       Bern  3008     4.5        108.0         NaN          NaN       2490.0

In [78]:
#Durchschnittsmiete 4.5 Zimmerwohnung in Holligen/Weissenstein
viereinhalbzimmer_hol_ws.bruttomiete.median()

2625.0

## 10. Ergebnisse für 3005: Kirchenfeld
#### Erkenntnis: Selbst hier toppen die 2-Zimmerwohnungen (5) alle anderen Grössen. Wenige Wohnungen auf dem Markt.
- Total freie Wohnungen: 16 
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 1992 (nur 3 Wohnungen)
- Durchschnittsmiete 4.5-Zimmerwohnung: CHF 3935 (4 Wohnungen)

In [79]:
#kirchenfeld
kirchenfeld = df_bern[df_bern.plz == 3005]
kirchenfeld.head()

objekt_id kategorie       objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
461    6120408   Wohnung      Bernastrasse 67       Bern  3005     4.5         95.0      2420.0        330.0       2750.0
464    6138149   Wohnung                  NaN       Bern  3005     2.0         50.0      2880.0          NaN       2880.0
467    6171016   Wohnung   Aegertenstrasse 53       Bern  3005     3.5        110.0      2650.0        320.0       2970.0
482    6254853   Wohnung                  NaN       Bern  3005     4.5        112.0      5748.0          NaN       5748.0
492    6295856   Wohnung  Schillingstrasse 34       Bern  3005     3.5         90.0      1700.0        200.0       1900.0

In [80]:
#Total freie Wohnungen kirchenfeld
kirchenfeld.zimmer.value_counts(ascending=False).head(10)

2.0    5
4.5    4
3.5    3
2.5    2
4.0    1
5.5    1
Name: zimmer, dtype: int64

In [81]:
kirchenfeld.shape

(16, 10)

In [82]:
#3.5-Zimmer-Wohnungen kirchenfeld (ACHTUNG: nur 3)
dreieinhalbzimmer_kirchenfeld = kirchenfeld[kirchenfeld.zimmer == 3.5]
dreieinhalbzimmer_kirchenfeld.head(5)

objekt_id kategorie       objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
467    6171016   Wohnung   Aegertenstrasse 53       Bern  3005     3.5        110.0      2650.0        320.0       2970.0
492    6295856   Wohnung  Schillingstrasse 34       Bern  3005     3.5         90.0      1700.0        200.0       1900.0
665    6364256   Wohnung                  NaN       Bern  3005     3.5          NaN      1992.0          NaN       1992.0

In [83]:
#Durchschnittsmiete 3.5-Zimmerwohnung Kirchenfeld
dreieinhalbzimmer_kirchenfeld.bruttomiete.median()

1992.0

In [84]:
#4.5-Zimmer-Wohnungen in kirchenfeld
viereinhalbzimmer_kirchenfeld = kirchenfeld[kirchenfeld.zimmer == 4.5]
viereinhalbzimmer_kirchenfeld.head(5)

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
461    6120408   Wohnung     Bernastrasse 67       Bern  3005     4.5         95.0      2420.0        330.0       2750.0
482    6254853   Wohnung                 NaN       Bern  3005     4.5        112.0      5748.0          NaN       5748.0
655    6355889   Wohnung  Kirchenfeldstr. 55       Bern  3005     4.5        107.0      2630.0        290.0       2920.0
657    6356299   Wohnung                 NaN       Bern  3005     4.5        112.0      4600.0        350.0       4950.0

In [85]:
#Durchschnittsmiete 4.5 Zimmerwohnung kirchenfeld
viereinhalbzimmer_kirchenfeld.bruttomiete.median()

3935.0

## 11. Ergebnisse für 3007: Mattenhof, Monbijou, Sandrain, Weissenbühl 
#### Erkenntnis: Hier dominieren die 2.5-Zi (18), 3-Zi (18) und 3.5-Zimmerwohnungen (10). Erneut wenig darüber.
- Total freie Wohnungen: 74 
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 1795 
- Durchschnittsmiete 4.5-Zimmerwohnung: CHF 2330 (basierend auf 5 Wohnungen)

In [86]:
#Mattenhof, Monbijou, Sandrain, Weissenbühl, vereinfacht mamo
mamo = df_bern[df_bern.plz == 3007]
mamo.head()

objekt_id kategorie         objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
116    6190683   Wohnung    Brunnmattstrasse 24       Bern  3007     2.5         55.0         NaN          NaN       1230.0
255    6334258   Wohnung  Brunnmattstrasse 20 A       Bern  3007     2.5         50.0      1205.0        190.0       1395.0
298    6361152   Wohnung       Gartenstrasse 16       Bern  3007     3.0         58.0         NaN          NaN       1506.0
304    6363394   Wohnung       Gartenstrasse 11       Bern  3007     2.5         55.0      1150.0        160.0       1310.0
442    2351482   Wohnung        Eigerstrasse 76       Bern  3007     3.5        115.0      2280.0        260.0       2540.0

In [87]:
#Total freie Wohnungen Mattenhof Monbijou etc. mamo
mamo.zimmer.value_counts(ascending=False).head(15)

3.0    18
2.5    18
3.5    10
2.0     9
1.0     8
4.5     5
4.0     4
1.5     2
Name: zimmer, dtype: int64

In [88]:
mamo.shape

(74, 10)

In [89]:
#3.5-Zimmer-Wohnungen Mattenhof mamo
dreieinhalbzimmer_mamo = mamo[mamo.zimmer == 3.5]
dreieinhalbzimmer_mamo.head(5)

objekt_id kategorie          objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
442    2351482   Wohnung         Eigerstrasse 76       Bern  3007     3.5        115.0      2280.0        260.0       2540.0
495    6300934   Wohnung          Friedheimweg 9       Bern  3007     3.5         78.0      1650.0        280.0       1930.0
496    6309185   Wohnung  Schwarzenburgstrasse 4       Bern  3007     3.5         70.0      1250.0        230.0       1480.0
513    6333927   Wohnung    Pestalozzistrasse 18       Bern  3007     3.5          NaN      1735.0        250.0       1985.0
699    6180775   Wohnung      Seftigenstrasse 54       Bern  3007     3.5         70.0      1450.0        285.0       1735.0

In [90]:
#Durchschnittsmiete 3.5-Zimmerwohnung mamo
dreieinhalbzimmer_mamo.bruttomiete.median()

1795.0

In [91]:
#4.5-Zimmer-Wohnungen in mamo
viereinhalbzimmer_mamo = mamo[mamo.zimmer == 4.5]
viereinhalbzimmer_mamo.head(5)

objekt_id kategorie       objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
471    6194700   Wohnung   Seftigenstrasse 30       Bern  3007     4.5        100.0      2100.0        330.0       2430.0
472    6194707   Wohnung   Seftigenstrasse 30       Bern  3007     4.5        100.0      2000.0        330.0       2330.0
524    5374601   Wohnung           Blockweg 8       Bern  3007     4.5         98.0      2030.0        270.0       2300.0
581    6273742   Wohnung           Blockweg 8       Bern  3007     4.5        146.0      2770.0        430.0       3200.0
743    6310833   Wohnung  Tscharnerstrasse 28       Bern  3007     4.5         94.0      1900.0        350.0       2250.0

In [92]:
#Durchschnittsmiete 4.5-Zimmerwohnung in mamo
viereinhalbzimmer_mamo.bruttomiete.median()

2330.0

## 12. Ergebnisse für 3015: Murifeld 
#### Erkenntnis: Wenig Wohnungen inseriert, nur wenig Preisunterschied zwischen einer 3.5- und 4.5-Zimmerwohnung.
- Total freie Wohnungen: 10 
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 2205 (nur 2 Wohnungen)
- Durchschnittsmiete 4.5-Zimmerwohnung: CHF 2230 (nur 3 Wohnungen)

In [93]:
#murifeld
murifeld = df_bern[df_bern.plz == 3015]
murifeld.head()

objekt_id kategorie        objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
459    6090084   Wohnung     Jupiterstrasse 41       Bern  3015     4.5          NaN      1750.0        350.0       2100.0
473    6207113   Wohnung     Weltpoststrasse 3       Bern  3015     2.5         67.0      1770.0        170.0       1940.0
488    6275368   Wohnung  Jupiterstrasse 29/05       Bern  3015     NaN          NaN       497.0         75.0        572.0
494    6299668   Wohnung     Jupiterstrasse 43       Bern  3015     5.5        115.0      1790.0        350.0       2140.0
644    6342679   Wohnung     Weltpoststrasse 3       Bern  3015     4.5        100.0      2370.0        250.0       2620.0

In [94]:
#Total freie Wohnungen murifeld
murifeld.zimmer.value_counts(ascending=False).head(15)

2.5    3
4.5    3
3.5    2
5.5    1
Name: zimmer, dtype: int64

In [95]:
murifeld.shape

(10, 10)

In [96]:
#3.5-Zimmer-Wohnungen murifeld
dreieinhalbzimmer_murifeld = murifeld[murifeld.zimmer == 3.5]
dreieinhalbzimmer_murifeld.head(5)

objekt_id kategorie     objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
650    6347727   Wohnung   Jupiterstrasse 7       Bern  3015     3.5         75.0      1540.0        240.0       1780.0
662    6363312   Wohnung  Weltpoststrasse 1       Bern  3015     3.5         93.0      2410.0        220.0       2630.0

In [97]:
#Durchschnittsmiete 3.5-Zimmer-Wohnungen murifeld (ACHTUNG: nur 2 Wohnungen)
dreieinhalbzimmer_murifeld.bruttomiete.median()

2205.0

In [98]:
#4.5-Zimmer-Wohnungen in murifeld
viereinhalbzimmer_murifeld = murifeld[murifeld.zimmer == 4.5]
viereinhalbzimmer_murifeld.head(5)

objekt_id kategorie     objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
459    6090084   Wohnung  Jupiterstrasse 41       Bern  3015     4.5          NaN      1750.0        350.0       2100.0
644    6342679   Wohnung  Weltpoststrasse 3       Bern  3015     4.5        100.0      2370.0        250.0       2620.0
647    6345203   Wohnung  Jupiterstrasse 31       Bern  3015     4.5          NaN      1850.0        380.0       2230.0

In [99]:
#Durchschnittsmiete 4.5-Zimmer-Wohnungen in murifeld
viereinhalbzimmer_murifeld.bruttomiete.median()

2230.0

## 13. Ergebnisse für 3019: Oberbottigen
#### Erkenntnis: Nur 2 Wohnungen inseriert.
- Total freie Wohnungen: 2
- Durchschnittsmiete 3.5-Zimmerwohnung: CHF 1400 (basierend auf 1 Wohnung)
- Durchschnittsmiete 4.5-Zimmerwohnung: CHF 1960 (basierend auf 1 Wohnung)

In [100]:
#oberbottigen
oberbottigen = df_bern[df_bern.plz == 3019]
oberbottigen.head()

objekt_id kategorie        objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
443    2524116   Wohnung    Oberbottigenweg 43       Bern  3019     3.5         87.0      1200.0        200.0       1400.0
993    6361609   Wohnung  Matzenriedstrasse 49       Bern  3019     4.5        105.0      1900.0         60.0       1960.0

In [101]:
#Total freie Wohnungen oberbottigen
oberbottigen.zimmer.value_counts(ascending=False).head(15)

4.5    1
3.5    1
Name: zimmer, dtype: int64

## 14. Ostermundigen

In [102]:
df_immoscout[df_immoscout.objekt_ort == 'Ostermundigen']

objekt_id kategorie                                     objekt_strasse     objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
0      1108404   Wohnung                           Oberfeld, Jurablickweg 7  Ostermundigen  3072     3.5         76.0      1680.0        240.0       1920.0
2      3255700   Wohnung                                    Gerbestrasse 11  Ostermundigen  3072     3.0          NaN      1100.0        150.0       1250.0
6      4941186   Wohnung                                      Bachstrasse 6  Ostermundigen  3072     2.5         51.0      1110.0        180.0       1290.0
10     5321353   Wohnung                                 Obere Zollgasse 68  Ostermundigen  3072     3.5          NaN      1220.0        230.0       1450.0
12     5478472   Wohnung                                      Ringstrasse 9  Ostermundigen  3072     1.0         25.0       700.0        120.0        820.0
17     5857618   Wohnung                                         Flurweg 34  Ostermundigen  3072     3.0         56.0      1150.0        220.0       1370.0
18     5924472   Wohnung                                         Flurweg 34  Ostermundigen  3072     3.0         56.0      1150.0        220.0       1370.0
20     6053024   Wohnung                                   Gerbestrasse 11a  Ostermundigen  3072     3.5          NaN      1270.0        220.0       1490.0
22     6112079   Wohnung                                     Ringstrasse 11  Ostermundigen  3072     3.5         55.0      1250.0        180.0       1430.0
24     6128253   Wohnung                                       Winkelweg 12  Ostermundigen  3072     2.0         45.0      1300.0        150.0       1450.0
28     6205870   Wohnung                                 Obere Zollgasse 35  Ostermundigen  3072     3.5         60.0      1300.0        220.0       1520.0
31     6244359   Wohnung                                 Dennigkofenweg 185  Ostermundigen  3072     3.5         84.0      1700.0        250.0       1950.0
39     6281777   Wohnung                                    Gerbestrasse 21  Ostermundigen  3072     4.0          NaN      1100.0        250.0       1350.0
40     6282244   Wohnung                                 Oberer Flurweg 124  Ostermundigen  3072     3.5          NaN      1380.0        240.0       1620.0
41     6288079      Haus                               Obere Zollgasse 59 A  Ostermundigen  3072     4.5         90.0         NaN          NaN       2450.0
42     6289951   Wohnung                                     Bachstrasse 12  Ostermundigen  3072     3.5         68.0      1240.0        250.0       1490.0
44     6296870   Wohnung                                    Ringstrasse 11a  Ostermundigen  3072     3.5         55.0      1140.0        210.0       1350.0
45     6299322   Wohnung                                    Gerbestrasse 24  Ostermundigen  3072     3.0          NaN      1100.0        300.0       1400.0
46     6299331   Wohnung                                    Gerbestrasse 22  Ostermundigen  3072     3.0          NaN      1070.0        250.0       1320.0
52     6328661   Wohnung                                 Dennigkofenweg 160  Ostermundigen  3072     3.0         67.0      1200.0        200.0       1400.0
53     6329378   Wohnung                                      Ringstrasse 3  Ostermundigen  3072     3.5          NaN      1150.0        220.0       1370.0
57     6339016   Wohnung                                     Güterstrasse 3  Ostermundigen  3072     3.5         86.0      1790.0        270.0       2060.0
62     6347276   Wohnung                                 Dennigkofenweg 183  Ostermundigen  3072     4.5        117.0      2150.0        300.0       2450.0
63     6348177   Wohnung                                 Oberdorfstrasse 34  Ostermundigen  3072     3.0         72.0      1200.0        200.0       1400.0
64     6348785   Wohnung                                 Obere Zollgasse 34  Ostermundigen  3072     3.5 

In [103]:
df_ostermundigen = df_immoscout[df_immoscout.objekt_ort == 'Ostermundigen']
df_ostermundigen.head(10)

objekt_id kategorie            objekt_strasse     objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
0     1108404   Wohnung  Oberfeld, Jurablickweg 7  Ostermundigen  3072     3.5         76.0      1680.0        240.0       1920.0
2     3255700   Wohnung           Gerbestrasse 11  Ostermundigen  3072     3.0          NaN      1100.0        150.0       1250.0
6     4941186   Wohnung             Bachstrasse 6  Ostermundigen  3072     2.5         51.0      1110.0        180.0       1290.0
10    5321353   Wohnung        Obere Zollgasse 68  Ostermundigen  3072     3.5          NaN      1220.0        230.0       1450.0
12    5478472   Wohnung             Ringstrasse 9  Ostermundigen  3072     1.0         25.0       700.0        120.0        820.0
17    5857618   Wohnung                Flurweg 34  Ostermundigen  3072     3.0         56.0      1150.0        220.0       1370.0
18    5924472   Wohnung                Flurweg 34  Ostermundigen  3072     3.0         56.0      1150.0        220.0       1370.0
20    6053024   Wohnung          Gerbestrasse 11a  Ostermundigen  3072     3.5          NaN      1270.0        220.0       1490.0
22    6112079   Wohnung            Ringstrasse 11  Ostermundigen  3072     3.5         55.0      1250.0        180.0       1430.0
24    6128253   Wohnung              Winkelweg 12  Ostermundigen  3072     2.0         45.0      1300.0        150.0       1450.0

In [105]:
#Anz Wohnungen in Ostermundigen
df_ostermundigen.shape

(108, 10)

In [106]:
#Anz Wohnungen in Ostermundigen mit unbekannter Bruttomiete
df_ostermundigen[df_ostermundigen.bruttomiete.isnull()] 

objekt_id kategorie  objekt_strasse     objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
626    6363013   Wohnung  Ringstrasse 25  Ostermundigen  3072     3.5         58.0         NaN          NaN          NaN

In [108]:
#Um Verzerrungen bei den Durchschnittsmieten zu vermeiden, droppen wir die Wohnungen mit unbekannter Bruttomiete
df_ostermundigen.dropna(subset=['bruttomiete'])

objekt_id kategorie                                     objekt_strasse     objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
0      1108404   Wohnung                           Oberfeld, Jurablickweg 7  Ostermundigen  3072     3.5         76.0      1680.0        240.0       1920.0
2      3255700   Wohnung                                    Gerbestrasse 11  Ostermundigen  3072     3.0          NaN      1100.0        150.0       1250.0
6      4941186   Wohnung                                      Bachstrasse 6  Ostermundigen  3072     2.5         51.0      1110.0        180.0       1290.0
10     5321353   Wohnung                                 Obere Zollgasse 68  Ostermundigen  3072     3.5          NaN      1220.0        230.0       1450.0
12     5478472   Wohnung                                      Ringstrasse 9  Ostermundigen  3072     1.0         25.0       700.0        120.0        820.0
17     5857618   Wohnung                                         Flurweg 34  Ostermundigen  3072     3.0         56.0      1150.0        220.0       1370.0
18     5924472   Wohnung                                         Flurweg 34  Ostermundigen  3072     3.0         56.0      1150.0        220.0       1370.0
20     6053024   Wohnung                                   Gerbestrasse 11a  Ostermundigen  3072     3.5          NaN      1270.0        220.0       1490.0
22     6112079   Wohnung                                     Ringstrasse 11  Ostermundigen  3072     3.5         55.0      1250.0        180.0       1430.0
24     6128253   Wohnung                                       Winkelweg 12  Ostermundigen  3072     2.0         45.0      1300.0        150.0       1450.0
28     6205870   Wohnung                                 Obere Zollgasse 35  Ostermundigen  3072     3.5         60.0      1300.0        220.0       1520.0
31     6244359   Wohnung                                 Dennigkofenweg 185  Ostermundigen  3072     3.5         84.0      1700.0        250.0       1950.0
39     6281777   Wohnung                                    Gerbestrasse 21  Ostermundigen  3072     4.0          NaN      1100.0        250.0       1350.0
40     6282244   Wohnung                                 Oberer Flurweg 124  Ostermundigen  3072     3.5          NaN      1380.0        240.0       1620.0
41     6288079      Haus                               Obere Zollgasse 59 A  Ostermundigen  3072     4.5         90.0         NaN          NaN       2450.0
42     6289951   Wohnung                                     Bachstrasse 12  Ostermundigen  3072     3.5         68.0      1240.0        250.0       1490.0
44     6296870   Wohnung                                    Ringstrasse 11a  Ostermundigen  3072     3.5         55.0      1140.0        210.0       1350.0
45     6299322   Wohnung                                    Gerbestrasse 24  Ostermundigen  3072     3.0          NaN      1100.0        300.0       1400.0
46     6299331   Wohnung                                    Gerbestrasse 22  Ostermundigen  3072     3.0          NaN      1070.0        250.0       1320.0
52     6328661   Wohnung                                 Dennigkofenweg 160  Ostermundigen  3072     3.0         67.0      1200.0        200.0       1400.0
53     6329378   Wohnung                                      Ringstrasse 3  Ostermundigen  3072     3.5          NaN      1150.0        220.0       1370.0
57     6339016   Wohnung                                     Güterstrasse 3  Ostermundigen  3072     3.5         86.0      1790.0        270.0       2060.0
62     6347276   Wohnung                                 Dennigkofenweg 183  Ostermundigen  3072     4.5        117.0      2150.0        300.0       2450.0
63     6348177   Wohnung                                 Oberdorfstrasse 34  Ostermundigen  3072     3.0         72.0      1200.0        200.0       1400.0
64     6348785   Wohnung                                 Obere Zollgasse 34  Ostermundigen  3072     3.5 

In [109]:
#Neue Datenbank enthält 107 Wohnungen in Ostermundigen mit Angaben zur Bruttomiete
df_ostermundigen = df_ostermundigen.dropna(subset=['bruttomiete'])
df_ostermundigen.shape

(107, 10)

# Ergebnisse für Ostermundigen nach Grösse und Miete
Wie viele Wohnungen sind in Ostermundigen total auf dem Markt (nach Immoscout)? 
- 107 Wohnungen total, davon: 31 3.5-Zimmerwohnungen und 16 Viereinhalb-Z-Wohnungen

Wie hoch ist die durchschnittliche Miete in Ostermundigen für 3.5- und 4.5-Zimmerwohnung?
- 1500 Franken für eine 3.5-Z-Wohnung
- 1952.50 Franken fpr eine 4.5-Z-Wohnung

Grössen sonst: Immerhin 4 5.5-Zimmerwohnungen und sogar eine 6-Zimmerwohnung auf dem Markt

In [116]:
#Wohnungen total in Ostermundigen
df_ostermundigen.zimmer.value_counts(ascending=False).head(15)

3.5    31
3.0    21
4.5    16
2.5    15
4.0     6
2.0     6
5.5     4
1.0     4
1.5     2
6.0     1
Name: zimmer, dtype: int64

In [110]:
#3.5-Zimmer-Wohnungen in Ostermundigen
dreieinhalbzimmer_ostermundigen = df_ostermundigen[df_ostermundigen.zimmer == 3.5]
dreieinhalbzimmer_ostermundigen.head(5)

objekt_id kategorie            objekt_strasse     objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
0     1108404   Wohnung  Oberfeld, Jurablickweg 7  Ostermundigen  3072     3.5         76.0      1680.0        240.0       1920.0
10    5321353   Wohnung        Obere Zollgasse 68  Ostermundigen  3072     3.5          NaN      1220.0        230.0       1450.0
20    6053024   Wohnung          Gerbestrasse 11a  Ostermundigen  3072     3.5          NaN      1270.0        220.0       1490.0
22    6112079   Wohnung            Ringstrasse 11  Ostermundigen  3072     3.5         55.0      1250.0        180.0       1430.0
28    6205870   Wohnung        Obere Zollgasse 35  Ostermundigen  3072     3.5         60.0      1300.0        220.0       1520.0

In [111]:
#Total 3.5 Zimmerwohnungen in Ostermundigen
dreieinhalbzimmer_ostermundigen.shape

(31, 10)

In [112]:
#Durchschnittsmiete 3.5-Z in Ostermundigen:
dreieinhalbzimmer_ostermundigen.bruttomiete.median()

1500.0

In [113]:
#4.5-Zimmer-Wohnungen in Ostermundigen
viereinhalbzimmer_ostermundigen = df_ostermundigen[df_ostermundigen.zimmer == 4.5]
viereinhalbzimmer_ostermundigen.head(5)

objekt_id kategorie                                     objekt_strasse     objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
41     6288079      Haus                               Obere Zollgasse 59 A  Ostermundigen  3072     4.5         90.0         NaN          NaN       2450.0
62     6347276   Wohnung                                 Dennigkofenweg 183  Ostermundigen  3072     4.5        117.0      2150.0        300.0       2450.0
72     6355952   Wohnung                                Obere Zollgasse 51B  Ostermundigen  3072     4.5          NaN      1300.0        250.0       1550.0
416    6295902   Wohnung  Wohnen mit Service und Dienstleistungen, Grube...  Ostermundigen  3072     4.5        109.0      2140.0        270.0       2410.0
439    6334297   Wohnung                                     Bernstrasse 25  Ostermundigen  3072     4.5        108.0      2420.0        350.0       2770.0

In [114]:
#Total 4.5 Zimmerwohnungen in Ostermundigen
viereinhalbzimmer_ostermundigen.shape

(16, 10)

In [115]:
#Durchschnittsmiete 4.5-Z in Ostermundigen:
viereinhalbzimmer_ostermundigen.bruttomiete.median()

1952.5

# 15. Ergebnisse für Ittigen 
Wie viele Wohnungen sind in Ittigen total auf dem Markt (nach Immoscout)? 
- 52 Wohnungen total, davon: 12 3.5-Zimmerwohnungen und 8 Viereinhalb-Z-Wohnungen

Wie hoch ist die durchschnittliche Miete in Ittigen für 3.5- und 4.5-Zimmerwohnung?
- 1690 Franken für eine 3.5-Z-Wohnung
- 1925 Franken fpr eine 4.5-Z-Wohnung

Bemerkung: Viele kleinere Wohnungen (2- und 3-Zimmerwohnungen)

In [117]:
df_ittigen = df_immoscout[df_immoscout.objekt_ort == 'Ittigen']
df_ittigen.head(10)

objekt_id kategorie         objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
518    4544895   Wohnung  Worblentalstrasse 105    Ittigen  3063     2.5         55.0      1250.0        100.0       1350.0
519    4780076   Wohnung       Obereyfeldweg 31    Ittigen  3063     4.0          NaN      1450.0        250.0       1700.0
522    5263085   Wohnung       Obereyfeldweg 33    Ittigen  3063     3.0          NaN      1190.0        170.0       1360.0
530    5754834   Wohnung       Im Gerbelacker 2    Ittigen  3063     4.5          NaN      1680.0        300.0       1980.0
555    6155597   Wohnung      Im Gerbelacker 12    Ittigen  3063     4.5          NaN      1680.0        300.0       1980.0
556    6158972   Wohnung       Obereyfeldweg 33    Ittigen  3063     3.0          NaN         NaN          NaN       1360.0
562    6194121   Wohnung       Untereyfeldweg 1    Ittigen  3063     3.5         78.0      1395.0        200.0       1595.0
567    6220761   Wohnung           Mittelweg 17    Ittigen  3063     2.5          NaN         NaN          NaN       1610.0
569    6235821   Wohnung    Kirschenackerweg 24    Ittigen  3063     4.0         96.0      2040.0        300.0       2340.0
575    6251279   Wohnung      Badhausstrasse 21    Ittigen  3063     2.5          NaN      1160.0        180.0       1340.0

In [118]:
#Anz Wohnungen in Ittigen
df_ittigen.shape

(54, 10)

In [122]:
#Anz Wohnungen in Ostermundigen mit unbekannter Bruttomiete
df_ittigen[df_ittigen.bruttomiete.isnull()] 

objekt_id kategorie objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
769    6338480   Wohnung       Talweg 2    Ittigen  3063     3.5         70.0         NaN          NaN          NaN
785    6345269   Wohnung      Talweg 15    Ittigen  3063     3.5        139.0         NaN          NaN          NaN

In [124]:
#Um Verzerrungen bei den Durchschnittsmieten zu vermeiden, droppen wir die Wohnungen mit unbekannter Bruttomiete
df_ittigen.dropna(subset=['bruttomiete'])

objekt_id kategorie         objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
518     4544895   Wohnung  Worblentalstrasse 105    Ittigen  3063     2.5         55.0      1250.0        100.0       1350.0
519     4780076   Wohnung       Obereyfeldweg 31    Ittigen  3063     4.0          NaN      1450.0        250.0       1700.0
522     5263085   Wohnung       Obereyfeldweg 33    Ittigen  3063     3.0          NaN      1190.0        170.0       1360.0
530     5754834   Wohnung       Im Gerbelacker 2    Ittigen  3063     4.5          NaN      1680.0        300.0       1980.0
555     6155597   Wohnung      Im Gerbelacker 12    Ittigen  3063     4.5          NaN      1680.0        300.0       1980.0
556     6158972   Wohnung       Obereyfeldweg 33    Ittigen  3063     3.0          NaN         NaN          NaN       1360.0
562     6194121   Wohnung       Untereyfeldweg 1    Ittigen  3063     3.5         78.0      1395.0        200.0       1595.0
567     6220761   Wohnung           Mittelweg 17    Ittigen  3063     2.5          NaN         NaN          NaN       1610.0
569     6235821   Wohnung    Kirschenackerweg 24    Ittigen  3063     4.0         96.0      2040.0        300.0       2340.0
575     6251279   Wohnung      Badhausstrasse 21    Ittigen  3063     2.5          NaN      1160.0        180.0       1340.0
580     6265689   Wohnung     Obereyfeldweg 25 A    Ittigen  3063     2.5          NaN      1100.0        200.0       1300.0
671     4286504   Wohnung     Längfeldstrasse 60    Ittigen  3063     4.0         85.0      1380.0        200.0       1580.0
672     4295199   Wohnung     Längfeldstrasse 68    Ittigen  3063     3.5          NaN      1150.0        270.0       1420.0
673     4321112   Wohnung      Ittigenstrasse 8a    Ittigen  3063     3.5         85.0      1450.0        345.0       1795.0
675     4760281   Wohnung     Längfeldstrasse 58    Ittigen  3063     3.0          NaN      1160.0        130.0       1290.0
679     5484301   Wohnung     Grauholzstrasse 62    Ittigen  3063     3.0         63.0      1090.0        200.0       1290.0
680     5753152   Wohnung            Eichenweg 4    Ittigen  3063     2.5         80.0      1580.0        250.0       1830.0
682     5863091   Wohnung            Eichenweg 2    Ittigen  3063     2.5         66.0      1590.0        220.0       1810.0
685     5992973   Wohnung         Jurastrasse 15    Ittigen  3063     2.5         84.0      1420.0        250.0       1670.0
687     6047858   Wohnung     Längfeldstrasse 16    Ittigen  3063     3.0         63.0      1240.0        250.0       1490.0
693     6118672   Wohnung     Längfeldstrasse 62    Ittigen  3063     3.0         67.0      1320.0        190.0       1510.0
697     6169317   Wohnung         Jurastrasse 65    Ittigen  3063     2.5         84.0      1340.0        190.0       1530.0
705     6197620   Wohnung         Jurastrasse 15    Ittigen  3063     4.5         98.0      1540.0        270.0       1810.0
716     6225670   Wohnung      Ittigenstrasse 10    Ittigen  3063     3.5         94.0      2000.0        250.0       2250.0
731     6286867   Wohnung    Grauholzstrasse 58a    Ittigen  3063     4.5        100.0      1680.0        300.0       1980.0
732     6287251   Wohnung         Jurastrasse 25    Ittigen  3063     5.5        112.0      1850.0        330.0       2180.0
733     6287252   Wohnung         Jurastrasse 67    Ittigen  3063     2.5         65.0      1140.0        180.0       1320.0
734     6289904   Wohnung         Asylstrasse 38    Ittigen  3063     3.5         81.0      1255.0        230.0       1485.0
737     6293342   Wohnung      Talgut-Zentrum 38    Ittigen  3063     3.5         82.0      1560.0        180.0       1740.0
745     6316303   Wohnung       Talgutzentrum 26    Ittigen  3063     3.5         83.0      1430.0        240.0       1670.0
761     6332188   Wohnung      Badhausstrasse 21    Ittigen  3063     3.0         52.0      1270.0        190.0       1460.0
783   

In [125]:
#Neue Datenbank enthält 52 Wohnungen in Ittigen mit Angaben zur Bruttomiete
df_ittigen = df_ittigen.dropna(subset=['bruttomiete'])
df_ittigen.shape

(52, 10)

In [126]:
#Wohnungen total in Ittigen
df_ittigen.zimmer.value_counts(ascending=False).head(15)

3.5    12
3.0    12
2.5    11
4.5     8
4.0     5
1.5     1
1.0     1
2.0     1
5.5     1
Name: zimmer, dtype: int64

In [127]:
#3.5-Zimmer-Wohnungen in Ittigen
dreieinhalbzimmer_ittigen = df_ittigen[df_ittigen.zimmer == 3.5]
dreieinhalbzimmer_ittigen.head(5)

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
562    6194121   Wohnung    Untereyfeldweg 1    Ittigen  3063     3.5         78.0      1395.0        200.0       1595.0
672    4295199   Wohnung  Längfeldstrasse 68    Ittigen  3063     3.5          NaN      1150.0        270.0       1420.0
673    4321112   Wohnung   Ittigenstrasse 8a    Ittigen  3063     3.5         85.0      1450.0        345.0       1795.0
716    6225670   Wohnung   Ittigenstrasse 10    Ittigen  3063     3.5         94.0      2000.0        250.0       2250.0
734    6289904   Wohnung      Asylstrasse 38    Ittigen  3063     3.5         81.0      1255.0        230.0       1485.0

In [128]:
#Total 3.5 Zimmerwohnungen in Ittigen
dreieinhalbzimmer_ittigen.shape

(12, 10)

In [129]:
#Durchschnittsmiete 3.5-Z in Ittigen:
dreieinhalbzimmer_ittigen.bruttomiete.median()

1690.0

In [130]:
#4.5-Zimmer-Wohnungen in Ittigen
viereinhalbzimmer_ittigen = df_ittigen[df_ittigen.zimmer == 4.5]
viereinhalbzimmer_ittigen.head(5)

objekt_id kategorie       objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
530    5754834   Wohnung     Im Gerbelacker 2    Ittigen  3063     4.5          NaN      1680.0        300.0       1980.0
555    6155597   Wohnung    Im Gerbelacker 12    Ittigen  3063     4.5          NaN      1680.0        300.0       1980.0
705    6197620   Wohnung       Jurastrasse 15    Ittigen  3063     4.5         98.0      1540.0        270.0       1810.0
731    6286867   Wohnung  Grauholzstrasse 58a    Ittigen  3063     4.5        100.0      1680.0        300.0       1980.0
808    6356213   Wohnung    Im Gerbelacker 14    Ittigen  3063     4.5          NaN      1600.0        270.0       1870.0

In [131]:
#Total 4.5 Zimmerwohnungen in Ittigen
viereinhalbzimmer_ittigen.shape

(8, 10)

In [132]:
#Durchschnittsmiete 4.5-Z in Ittigen:
viereinhalbzimmer_ittigen.bruttomiete.median()

1925.0

# 16. Ergebnisse für Gümligen 
Wie viele Wohnungen sind in Gümligen total auf dem Markt (nach Immoscout)? 
- 40 Wohnungen total, davon: 16 3.5-Zimmerwohnungen und 12 4.5-Zimmerwohnungen

Wie hoch ist die durchschnittliche Miete in Ittigen für 3.5- und 4.5-Zimmerwohnung?
- 1707.50 Franken für eine 3.5-Z-Wohnung
- 2289 Franken für eine 4.5-Z-Wohnung

In [133]:
df_guemligen = df_immoscout[df_immoscout.objekt_ort == 'Gümligen']
df_guemligen.head(10)

objekt_id kategorie        objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
162    5588482   Wohnung          Sonnenweg 30   Gümligen  3073     4.5        100.0      1818.0        260.0       2078.0
180    6244810   Wohnung         Sonnenweg 32a   Gümligen  3073     4.5         94.0         NaN          NaN       2580.0
201    6319300   Wohnung  Tannackerstrasse 28A   Gümligen  3073     3.5          NaN      1490.0        290.0       1780.0
218    6341138   Wohnung         Sonnenweg 24A   Gümligen  3073     3.5         80.0      1500.0        215.0       1715.0
223    6346389   Wohnung         Feldstrasse 3   Gümligen  3073     2.0          NaN       970.0        180.0       1150.0
447    4845148   Wohnung           Eigerweg 30   Gümligen  3073     4.5          NaN      1400.0        380.0       1780.0
469    6178972   Wohnung      Dennigkofenweg 1   Gümligen  3073     3.0          NaN      1500.0        240.0       1740.0
474    6216056   Wohnung      Dennigkofenweg 1   Gümligen  3073     2.5         57.0      1150.0        200.0       1350.0
479    6243521   Wohnung          Brüggliweg 9   Gümligen  3073     3.0         54.0      1100.0        200.0       1300.0
480    6250999   Wohnung      Dennigkofenweg 7   Gümligen  3073     4.5        110.0      2500.0        250.0       2750.0

In [135]:
#Anz Wohnungen in Gümligen
df_guemligen.shape

(40, 10)

In [136]:
#Anz Wohnungen in Gümligen mit unbekannter Bruttomiete
df_guemligen[df_guemligen.bruttomiete.isnull()] 

Empty DataFrame
Columns: [objekt_id, kategorie, objekt_strasse, objekt_ort, plz, zimmer, nutzflaeche, nettomiete, nebenkosten, bruttomiete]
Index: []

In [137]:
#Wohnungen total in Gümligen
df_guemligen.zimmer.value_counts(ascending=False).head(15)

3.5    16
4.5    12
2.5     3
3.0     3
5.0     2
4.0     1
5.5     1
1.0     1
2.0     1
Name: zimmer, dtype: int64

In [138]:
#3.5-Zimmer-Wohnungen in Gümligen
dreieinhalbzimmer_guemligen = df_guemligen[df_guemligen.zimmer == 3.5]
dreieinhalbzimmer_guemligen.head(5)

objekt_id kategorie        objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
201    6319300   Wohnung  Tannackerstrasse 28A   Gümligen  3073     3.5          NaN      1490.0        290.0       1780.0
218    6341138   Wohnung         Sonnenweg 24A   Gümligen  3073     3.5         80.0      1500.0        215.0       1715.0
483    6258945   Wohnung       Worbstrasse 137   Gümligen  3073     3.5         78.0      1400.0        300.0       1700.0
511    6333594   Wohnung      Dennigkofenweg 3   Gümligen  3073     3.5         70.0      1300.0        180.0       1480.0
585    6291330   Wohnung     Dennigkofenweg 77   Gümligen  3073     3.5          NaN      1450.0        240.0       1690.0

In [139]:
#Durchschnittsmiete 3.5-Z in Gümligen:
dreieinhalbzimmer_guemligen.bruttomiete.median()

1707.5

In [140]:
#4.5-Zimmer-Wohnungen in Gümligen
viereinhalbzimmer_guemligen = df_guemligen[df_guemligen.zimmer == 4.5]
viereinhalbzimmer_guemligen.head(5)

objekt_id kategorie     objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
162    5588482   Wohnung       Sonnenweg 30   Gümligen  3073     4.5        100.0      1818.0        260.0       2078.0
180    6244810   Wohnung      Sonnenweg 32a   Gümligen  3073     4.5         94.0         NaN          NaN       2580.0
447    4845148   Wohnung        Eigerweg 30   Gümligen  3073     4.5          NaN      1400.0        380.0       1780.0
480    6250999   Wohnung   Dennigkofenweg 7   Gümligen  3073     4.5        110.0      2500.0        250.0       2750.0
525    5409409   Wohnung  Dennigkofenweg 77   Gümligen  3073     4.5          NaN      1700.0        250.0       1950.0

In [141]:
#Durchschnittsmiete 4.5-Zimmerwohnung in Gümligen:
viereinhalbzimmer_guemligen.bruttomiete.median()

2289.0

# 17. Ergebnisse für Wabern 
Wie viele Wohnungen sind in Wabern total auf dem Markt (nach Immoscout)? 
- 40 Wohnungen total, davon: 13 3.5-Zimmerwohnungen und 3 4.5-Zimmerwohnungen

Wie hoch ist die durchschnittliche Miete in Wabern für 3.5- und 4.5-Zimmerwohnung?
- 1965 Franken für eine 3.5-Z-Wohnung
- 2330 Franken für eine 4.5-Z-Wohnung (nur 3 Wohnungen)

Bemerkung: Am zweithäufigsten 1-Zimmerwohnungen (10)

In [142]:
df_wabern = df_immoscout[df_immoscout.objekt_ort == 'Wabern']
df_wabern.head(10)

objekt_id kategorie             objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
155    4195852   Wohnung            Alpenstrasse 49     Wabern  3084     2.5         90.0      1900.0        150.0       2050.0
157    4342419   Wohnung             Bächtelenweg 5     Wabern  3084     3.5         94.0      1845.0        250.0       2095.0
159    5051571   Wohnung            Bächtelenweg 11     Wabern  3084     3.5         82.0      1665.0        300.0       1965.0
165    5786149   Wohnung           Looserstrasse 12     Wabern  3084     4.0         82.0      1465.0        225.0       1690.0
172    6194094   Wohnung           Kirchstrasse 140     Wabern  3084     3.0         65.0      1300.0        250.0       1550.0
174    6221354   Wohnung            Looserstrasse 2     Wabern  3084     4.0         82.0      1360.0        230.0       1590.0
175    6223602   Wohnung        Seftigenstrasse 226     Wabern  3084     3.0         57.0      1260.0        220.0       1480.0
176    6225251   Wohnung  untere Bernblickstrasse 2     Wabern  3084     2.5          NaN      1120.0        220.0       1340.0
190    6289498   Wohnung                        NaN     Wabern  3084     1.0         30.0      1320.0          NaN       1320.0
191    6294417   Wohnung           Kirchstrasse 150     Wabern  3084     3.5         76.0      1395.0        300.0       1695.0

In [143]:
#Anz Wohnungen in Wabern
df_wabern.shape

(40, 10)

In [144]:
#Anz Wohnungen in Wabern mit unbekannter Bruttomiete
df_wabern[df_wabern.bruttomiete.isnull()] 

Empty DataFrame
Columns: [objekt_id, kategorie, objekt_strasse, objekt_ort, plz, zimmer, nutzflaeche, nettomiete, nebenkosten, bruttomiete]
Index: []

In [145]:
#Wohnungen total in Wabern
df_wabern.zimmer.value_counts(ascending=False).head(15)

3.5    13
1.0    10
2.0     4
3.0     4
4.5     3
2.5     3
4.0     2
5.5     1
Name: zimmer, dtype: int64

In [146]:
#3.5-Zimmer-Wohnungen in Wabern
dreieinhalbzimmer_wabern = df_wabern[df_wabern.zimmer == 3.5]
dreieinhalbzimmer_wabern.head(5)

objekt_id kategorie    objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
157    4342419   Wohnung    Bächtelenweg 5     Wabern  3084     3.5         94.0      1845.0        250.0       2095.0
159    5051571   Wohnung   Bächtelenweg 11     Wabern  3084     3.5         82.0      1665.0        300.0       1965.0
191    6294417   Wohnung  Kirchstrasse 150     Wabern  3084     3.5         76.0      1395.0        300.0       1695.0
206    6326291   Wohnung  Looserstrasse 21     Wabern  3084     3.5         74.0      1410.0        240.0       1650.0
226    6350969   Wohnung  Kirchstrasse 142     Wabern  3084     3.5         76.0      1350.0        250.0       1600.0

In [147]:
#Durchschnittsmiete 3.5-Z in Wabern:
dreieinhalbzimmer_wabern.bruttomiete.median()

1965.0

In [148]:
#4.5-Zimmer-Wohnungen in Wabern
viereinhalbzimmer_wabern = df_wabern[df_wabern.zimmer == 4.5]
viereinhalbzimmer_wabern.head(5)

objekt_id kategorie       objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
372    6365083   Wohnung     Nesslerenweg 108     Wabern  3084     4.5        157.0      3575.0        420.0       3995.0
976    6355146   Wohnung       Funkstrasse 99     Wabern  3084     4.5        112.0      1640.0        300.0       1940.0
998    6363331   Wohnung  Sandrainstrasse 111     Wabern  3084     4.5        133.0      1950.0        380.0       2330.0

In [149]:
#Durchschnittsmiete 4.5-Zimmer in Wabern
viereinhalbzimmer_wabern.bruttomiete.median()

2330.0

# 18. Ergebnisse für Liebefeld
Wie viele Wohnungen sind in Liebefeld total auf dem Markt (nach Immoscout)?

- 36 Wohnungen total, davon: 7 3.5-Zimmerwohnungen und 4 4.5-Zimmerwohnungen

Wie hoch ist die durchschnittliche Miete in Liebefeld für 3.5- und 4.5-Zimmerwohnung?

- 1800 Franken für eine 3.5-Z-Wohnung
- 2020 Franken für eine 4.5-Z-Wohnung (nur 4 Wohnungen)

In [150]:
df_liebefeld = df_immoscout[df_immoscout.objekt_ort == 'Liebefeld']
df_liebefeld.head(10)

objekt_id kategorie          objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
153    2223600   Wohnung  Wabersackerstrasse 37a  Liebefeld  3097     3.0          NaN      1230.0        180.0       1410.0
154    3940383   Wohnung      Stationsstrasse 21  Liebefeld  3097     1.0         30.0       610.0        100.0        710.0
156    4267914   Wohnung      Wabersackerstr. 57  Liebefeld  3097     3.5         90.0      1560.0        240.0       1800.0
179    6244285   Wohnung       Könizstrasse 267A  Liebefeld  3097     2.5         62.0      1230.0        210.0       1440.0
183    6250661   Wohnung   Wabersackerstrasse 87  Liebefeld  3097     2.5         56.0      1150.0        220.0       1370.0
187    6275318   Wohnung   Wabersackerstrasse 65  Liebefeld  3097     3.0         70.0         NaN          NaN       1490.0
193    6300959   Wohnung   Wabersackerstrasse 27  Liebefeld  3097     2.5          NaN      1250.0        200.0       1450.0
196    6305043   Wohnung   Wabersackerstrasse 27  Liebefeld  3097     3.5          NaN      1450.0        220.0       1670.0
207    6327910      Haus      Feldrainstrasse 61  Liebefeld  3097     7.5        240.0      4800.0          NaN          NaN
220    6344933   Wohnung   Wabersackerstrasse 26  Liebefeld  3097     2.5         54.0      1050.0        180.0       1230.0

In [151]:
#Anz Wohnungen in Liebefeld
df_liebefeld.shape

(37, 10)

In [163]:
#Anz Wohnungen in Liebefeld mit unbekannter Bruttomiete. Ergebenis: 1
df_liebefeld[df_liebefeld.bruttomiete.isnull()] 

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
207    6327910      Haus  Feldrainstrasse 61  Liebefeld  3097     7.5        240.0      4800.0          NaN          NaN

In [164]:
#Neue Datenbank enthält 52 Wohnungen in Liebefeld mit Angaben zur Bruttomiete
df_liebefeld = df_liebefeld.dropna(subset=['bruttomiete'])
df_liebefeld.shape

(36, 10)

In [165]:
#Wohnungen total in Liebefeld
df_liebefeld.zimmer.value_counts(ascending=False).head(15)

2.5    15
3.5     7
4.5     4
3.0     3
1.5     2
1.0     2
5.5     1
2.0     1
Name: zimmer, dtype: int64

In [156]:
#3.5-Zimmer-Wohnungen in Liebefeld
dreieinhalbzimmer_liebefeld = df_liebefeld[df_liebefeld.zimmer == 3.5]
dreieinhalbzimmer_liebefeld.head(10)

objekt_id kategorie           objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
156     4267914   Wohnung       Wabersackerstr. 57  Liebefeld  3097     3.5         90.0      1560.0        240.0       1800.0
196     6305043   Wohnung    Wabersackerstrasse 27  Liebefeld  3097     3.5          NaN      1450.0        220.0       1670.0
231     6354258   Wohnung    Wabersackerstrasse 15  Liebefeld  3097     3.5          NaN      1200.0        250.0       1450.0
711     6215786   Wohnung             Thomasweg 23  Liebefeld  3097     3.5         69.0      1120.0        230.0       1350.0
973     6352933   Wohnung         Waldeggstrasse 7  Liebefeld  3097     3.5         79.0      1605.0        220.0       1825.0
989     6360315   Wohnung  Schwarzenburgstrasse 73  Liebefeld  3097     3.5         98.0      2000.0        290.0       2290.0
1001    6363565   Wohnung         Wilkerstrasse 24  Liebefeld  3097     3.5        122.0      2440.0        250.0       2690.0

In [166]:
#Durchschnittsmiete 3.5-Zimmerwohnung im Liebefeld
dreieinhalbzimmer_liebefeld.bruttomiete.median()

1800.0

In [157]:
#4.5-Zimmerwohnung im Liebefeld
viereinhalbzimmer_liebefeld = df_liebefeld[df_liebefeld.zimmer == 4.5]
viereinhalbzimmer_liebefeld.head(5)

objekt_id kategorie           objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
712    6215787   Wohnung             Thomasweg 19  Liebefeld  3097     4.5         80.0      1190.0        250.0       1440.0
725    6265852   Wohnung               Fuchsweg 7  Liebefeld  3097     4.5          NaN      1700.0        400.0       2100.0
729    6284163   Wohnung           Hessstrasse 39  Liebefeld  3097     4.5          NaN      1670.0        270.0       1940.0
730    6285800   Wohnung  Schwarzenburgstrasse 73  Liebefeld  3097     4.5         99.0      2050.0        290.0       2340.0

In [167]:
#Durchschnittsmiete 4.5 Zimmerwohnung im Liebefeld
viereinhalbzimmer_liebefeld.bruttomiete.median()

2020.0

# 19. Ergebnisse für Muri
Wie viele Wohnungen sind in Muri total auf dem Markt (nach Immoscout)?

- 28 Wohnungen total, davon: 6 3.5-Zimmerwohnungen und 7 4.5-Zimmerwohnungen

Wie hoch ist die durchschnittliche Miete in Muri für 3.5- und 4.5-Zimmerwohnung?

- 2110 Franken für eine 3.5-Z-Wohnung
- 2200 Franken für eine 4.5-Z-Wohnung

Bemerkung: Am meisten sind hier grössere Wohnungen auf dem Markt wie 4.5 Zimmer (7), 3.5 Zimmer (6) und 5.5 Zimmer (5). 

In [160]:
df_muri = df_immoscout[df_immoscout.objekt_ort == 'Muri b. Bern']
df_muri.head(10)

objekt_id kategorie        objekt_strasse    objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
163    5694839   Wohnung  Kirchackerstrasse 15  Muri b. Bern  3074     3.5        140.0      4450.0        520.0       4970.0
164    5699583   Wohnung   Pourtalèsstrasse 66  Muri b. Bern  3074     2.0        113.0      1700.0        200.0       1900.0
173    6194111   Wohnung       Thunstrasse 192  Muri b. Bern  3074     5.5        107.0      1675.0        320.0       1995.0
178    6244155   Wohnung        Kräyigenweg 88  Muri b. Bern  3074     4.5          NaN      1900.0        300.0       2200.0
186    6275058   Wohnung       Thunstrasse 192  Muri b. Bern  3074     4.5         94.0      1650.0        260.0       1910.0
189    6281732   Wohnung        Kräyigenweg 18  Muri b. Bern  3074     3.0        116.0         NaN          NaN       2750.0
195    6304962   Wohnung   Breichtenstrasse 11  Muri b. Bern  3074     NaN          NaN       920.0        150.0       1070.0
202    6319577   Wohnung   Pourtalèsstrasse 50  Muri b. Bern  3074     5.5        181.0      3200.0        650.0       3850.0
203    6323084   Wohnung       Aebnitstrasse 4  Muri b. Bern  3074     5.5        126.0      2850.0        275.0       3125.0
210    6336089   Wohnung          Haldenweg 14  Muri b. Bern  3074     3.5          NaN      1910.0        260.0       2170.0

In [162]:
# Anz Wohnungen in Muri
df_muri.shape

(28, 10)

In [170]:
#Wohnungen total in Muri nach Grösse
df_muri.zimmer.value_counts(ascending=False).head(15)

4.5    7
3.5    6
5.5    5
3.0    3
2.0    3
2.5    1
4.0    1
5.0    1
Name: zimmer, dtype: int64

In [168]:
#Anz Wohnungen in Muri mit unbekannter Bruttomiete. Ergebenis: 0
df_muri[df_muri.bruttomiete.isnull()] 

Empty DataFrame
Columns: [objekt_id, kategorie, objekt_strasse, objekt_ort, plz, zimmer, nutzflaeche, nettomiete, nebenkosten, bruttomiete]
Index: []

In [169]:
#3.5-Zimmer-Wohnungen in Muri
dreieinhalbzimmer_muri = df_muri[df_muri.zimmer == 3.5]
dreieinhalbzimmer_muri.head(10)

objekt_id kategorie        objekt_strasse    objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
163    5694839   Wohnung  Kirchackerstrasse 15  Muri b. Bern  3074     3.5        140.0      4450.0        520.0       4970.0
210    6336089   Wohnung          Haldenweg 14  Muri b. Bern  3074     3.5          NaN      1910.0        260.0       2170.0
470    6180000   Wohnung        Worbstrasse 95  Muri b. Bern  3074     3.5          NaN      1350.0        220.0       1570.0
481    6251465   Wohnung        Worbstrasse 76  Muri b. Bern  3074     3.5         97.0      1329.0        280.0       1609.0
925    6299320   Wohnung   Aebnitstrasse 30a-c  Muri b. Bern  3074     3.5          NaN      2150.0        250.0       2400.0
965    6346895   Wohnung          Kranichweg 7  Muri b. Bern  3074     3.5         82.0      1850.0        200.0       2050.0

In [171]:
#Durchschnittsmiete 3.5 Zimmerwohnung in Muri:
dreieinhalbzimmer_muri.bruttomiete.median()

2110.0

In [174]:
#4.5-Zimmerwohnung in Muri:
viereinhalbzimmer_muri = df_muri[df_muri.zimmer == 4.5]
viereinhalbzimmer_muri.head (10)

objekt_id kategorie       objekt_strasse    objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
178    6244155   Wohnung       Kräyigenweg 88  Muri b. Bern  3074     4.5          NaN      1900.0        300.0       2200.0
186    6275058   Wohnung      Thunstrasse 192  Muri b. Bern  3074     4.5         94.0      1650.0        260.0       1910.0
219    6344856   Wohnung  Pourtalèsstrasse 15  Muri b. Bern  3074     4.5          NaN      2600.0        200.0       2800.0
221    6345883   Wohnung       Kräyigenweg 93  Muri b. Bern  3074     4.5        107.0      1850.0        300.0       2150.0
684    5959199   Wohnung          thunstrasse  Muri b. Bern  3074     4.5        120.0      1680.0        250.0       1930.0
695    6131708   Wohnung    Villettengässli 1  Muri b. Bern  3074     4.5        110.0      2250.0        300.0       2550.0
719    6260562   Wohnung        Belpstrasse 4  Muri b. Bern  3074     4.5        146.0      2400.0        340.0       2740.0

In [176]:
#Durchschnittsmiete 4.5-Zimmerwohnung in Muri:
viereinhalbzimmer_muri.bruttomiete.median()

2200.0

# 20. Ergebnisse für Schliern b. Köniz
Wie viele Wohnungen sind in Schliern total auf dem Markt (nach Immoscout)?

- 27 Wohnungen total, davon: 12 3.5-Zimmerwohnungen und 10 4.5-Zimmerwohnungen

Wie hoch ist die durchschnittliche Miete in Schliern für 3.5- und 4.5-Zimmerwohnung?

- 1725 Franken für eine 3.5-Z-Wohnung
- 2075 Franken für eine 4.5-Z-Wohnung

In [177]:
df_schliern = df_immoscout[df_immoscout.objekt_ort == 'Schliern b. Köniz']
df_schliern.head(10)

objekt_id kategorie            objekt_strasse         objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
309    5556714   Wohnung           Gaselstrasse 23  Schliern b. Köniz  3098     3.5         73.0      1420.0        300.0       1720.0
310    5714138   Wohnung            Buchholzweg 10  Schliern b. Köniz  3098     3.5         85.0      1300.0        220.0       1520.0
313    5885513   Wohnung              Froschweg 11  Schliern b. Köniz  3098     4.5        107.0      1780.0        360.0       2140.0
316    6102428   Wohnung               Froschweg 9  Schliern b. Köniz  3098     4.5        107.0      1810.0        360.0       2170.0
317    6105004   Wohnung        Talbodenstrasse 85  Schliern b. Köniz  3098     3.5         86.0      1650.0        300.0       1950.0
318    6125478   Wohnung            Schaufelweg 95  Schliern b. Köniz  3098     3.5         82.0      1480.0        250.0       1730.0
319    6126790   Wohnung             Plattenweg 32  Schliern b. Köniz  3098     3.5        100.0      1500.0        290.0       1790.0
327    6202518   Wohnung  Schwandenhubelstrasse 43  Schliern b. Köniz  3098     3.0         58.0      1260.0        230.0       1490.0
330    6257058   Wohnung             Fuhrenstr. 54  Schliern b. Köniz  3098     2.0         52.0      1250.0        190.0       1440.0
332    6264501   Wohnung        Muhlernstrasse 141  Schliern b. Köniz  3098     4.5        104.0      1408.0        250.0       1658.0

In [178]:
#Wie viele Wohnungen in Schliern?
df_schliern.shape

(27, 10)

In [182]:
#Nach Grösse:
df_schliern.zimmer.value_counts (ascending=False).head(5)

3.5    12
4.5    10
3.0     2
5.5     1
1.5     1
Name: zimmer, dtype: int64

In [183]:
#Anz Wohnungen in Schliern mit unbekannter Bruttomiete. Ergebenis: 0
df_schliern[df_schliern.bruttomiete.isnull()] 

Empty DataFrame
Columns: [objekt_id, kategorie, objekt_strasse, objekt_ort, plz, zimmer, nutzflaeche, nettomiete, nebenkosten, bruttomiete]
Index: []

In [184]:
#3.5-Zimmer-Wohnungen in Schliern
dreieinhalbzimmer_schliern = df_schliern[df_schliern.zimmer == 3.5]
dreieinhalbzimmer_schliern.head(10)

objekt_id kategorie         objekt_strasse         objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
309    5556714   Wohnung        Gaselstrasse 23  Schliern b. Köniz  3098     3.5         73.0      1420.0        300.0       1720.0
310    5714138   Wohnung         Buchholzweg 10  Schliern b. Köniz  3098     3.5         85.0      1300.0        220.0       1520.0
317    6105004   Wohnung     Talbodenstrasse 85  Schliern b. Köniz  3098     3.5         86.0      1650.0        300.0       1950.0
318    6125478   Wohnung         Schaufelweg 95  Schliern b. Köniz  3098     3.5         82.0      1480.0        250.0       1730.0
319    6126790   Wohnung          Plattenweg 32  Schliern b. Köniz  3098     3.5        100.0      1500.0        290.0       1790.0
337    6299538   Wohnung  Büschiackerstrasse 20  Schliern b. Köniz  3098     3.5         85.0      1525.0        170.0       1695.0
341    6307737   Wohnung          Plattenweg 40  Schliern b. Köniz  3098     3.5         75.0      1480.0        260.0       1740.0
343    6328229   Wohnung        Talbodenstrasse  Schliern b. Köniz  3098     3.5         89.0      2065.0        300.0       2365.0
345    6328240   Wohnung            Schaufelweg  Schliern b. Köniz  3098     3.5         87.0      1415.0        280.0       1695.0
347    6328252   Wohnung     Sollrütistrasse 28  Schliern b. Köniz  3098     3.5         84.0      1340.0        260.0       1600.0

In [185]:
#Durchschnittsmiete 3.5 Zimmerwohnung in Schliern:
dreieinhalbzimmer_schliern.bruttomiete.median()

1725.0

In [186]:
#4.5-Zimmer-Wohnungen in Schliern
viereinhalbzimmer_schliern = df_schliern[df_schliern.zimmer == 4.5]
viereinhalbzimmer_schliern.head(10)

objekt_id kategorie      objekt_strasse         objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
313    5885513   Wohnung        Froschweg 11  Schliern b. Köniz  3098     4.5        107.0      1780.0        360.0       2140.0
316    6102428   Wohnung         Froschweg 9  Schliern b. Köniz  3098     4.5        107.0      1810.0        360.0       2170.0
332    6264501   Wohnung  Muhlernstrasse 141  Schliern b. Köniz  3098     4.5        104.0      1408.0        250.0       1658.0
355    6339443   Wohnung       Spühlihalde 5  Schliern b. Köniz  3098     4.5        104.0      1750.0        270.0       2020.0
356    6339461   Wohnung       Spühlihalde 5  Schliern b. Köniz  3098     4.5        107.0      1760.0        300.0       2060.0
358    6339469   Wohnung       Spühlihalde 3  Schliern b. Köniz  3098     4.5        144.0      2020.0        330.0       2350.0
359    6339479   Wohnung       Spühlihalde 3  Schliern b. Köniz  3098     4.5        105.0      1750.0        240.0       1990.0
360    6339485   Wohnung       Spühlihalde 7  Schliern b. Köniz  3098     4.5        106.0      1760.0        330.0       2090.0
365    6352169   Wohnung  Sollrütistrasse 28  Schliern b. Köniz  3098     4.5        116.0      1745.0        290.0       2035.0
366    6352190   Wohnung  Sollrütistrasse 18  Schliern b. Köniz  3098     4.5        150.0      1950.0        360.0       2310.0

In [187]:
#Durchschnittsmiete 4.5-Zimmerwohnung in Schliern:
viereinhalbzimmer_schliern.bruttomiete.median()

2075.0

# 21. Ergebnisse für 3065 Bolligen
Wie viele Wohnungen sind in Bolligen total auf dem Markt (nach Immoscout)?

- 22 Wohnungen total, davon: 10 3.5-Zimmerwohnungen und 6 4.5-Zimmerwohnungen

Wie hoch ist die durchschnittliche Miete in Bolligen für 3.5- und 4.5-Zimmerwohnung?

- 2035 Franken für eine 3.5-Z-Wohnung
- 2010 Franken für eine 4.5-Z-Wohnung

In [188]:
df_bolligen = df_immoscout[df_immoscout.objekt_ort == 'Bolligen']
df_bolligen.head(10)

objekt_id kategorie         objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
515    2388764   Wohnung       Kirchstrasse 11a   Bolligen  3065     3.5          NaN      1280.0        250.0       1530.0
516    2579360   Wohnung    Bolligenstrasse 126   Bolligen  3065     5.0        145.0      2450.0        200.0       2650.0
529    5721081   Wohnung      Rörswilstrasse 62   Bolligen  3065     4.5          NaN      1720.0        250.0       1970.0
544    6065707   Wohnung  Lutertalstrasse 49-55   Bolligen  3065     3.5        104.0      1900.0        300.0       2200.0
549    6087299   Wohnung  Lutertalstrasse 49-55   Bolligen  3065     4.5        127.0      2190.0        350.0       2540.0
560    6185044   Wohnung      Kistlerstrasse 16   Bolligen  3065     3.5          NaN      1700.0        290.0       1990.0
563    6194974   Wohnung      Kistlerstrasse 43   Bolligen  3065     6.5          NaN      1980.0        500.0       2480.0
566    6213871   Wohnung    Hühnerbühlstrasse 4   Bolligen  3065     5.5        137.0      1850.0        270.0       2120.0
674    4578477   Wohnung         Dorfstrasse 91   Bolligen  3065     5.5        200.0      2700.0        350.0       3050.0
689    6087302   Wohnung     Lutertalstrasse 55   Bolligen  3065     5.5        145.0      2480.0        400.0       2880.0

In [189]:
#Anzahl Wohnungen in Bolligen
df_bolligen.shape

(23, 10)

In [190]:
#Nach Grösse:
df_bolligen.zimmer.value_counts(ascending=False).head(10)

3.5    10
4.5     6
5.5     3
1.0     1
2.5     1
6.5     1
5.0     1
Name: zimmer, dtype: int64

In [191]:
#Anz Wohnungen in Bolligen mit unbekannter Bruttomiete. Ergebenis: 1
df_bolligen[df_bolligen.bruttomiete.isnull()] 

objekt_id kategorie   objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
968    6349145   Wohnung  Chrottegässli 2   Bolligen  3065     1.0          NaN         NaN          NaN          NaN

In [192]:
#Abzug der 1 NaN Wohnung für die Neue Datenbank
df_bolligen = df_bolligen.dropna(subset=['bruttomiete'])
df_bolligen.shape

(22, 10)

In [193]:
#3.5-Zimmer-Wohnungen in Bolligen
dreieinhalbzimmer_bolligen = df_bolligen[df_bolligen.zimmer == 3.5]
dreieinhalbzimmer_bolligen.head(10)

objekt_id kategorie         objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
515    2388764   Wohnung       Kirchstrasse 11a   Bolligen  3065     3.5          NaN      1280.0        250.0       1530.0
544    6065707   Wohnung  Lutertalstrasse 49-55   Bolligen  3065     3.5        104.0      1900.0        300.0       2200.0
560    6185044   Wohnung      Kistlerstrasse 16   Bolligen  3065     3.5          NaN      1700.0        290.0       1990.0
706    6207110   Wohnung        Stampachgasse 6   Bolligen  3065     3.5        103.0      1430.0        320.0       1750.0
777    6341292   Wohnung   Hühnerbühlstrasse 21   Bolligen  3065     3.5         84.0      1050.0        250.0       1300.0
778    6341462   Wohnung        Lutertalpark 10   Bolligen  3065     3.5         85.0      1876.0        340.0       2216.0
792    6348334   Wohnung                    NaN   Bolligen  3065     3.5        145.0      2950.0        320.0       3270.0
793    6348430   Wohnung  Hühnerbühlstrasse 161   Bolligen  3065     3.5         92.0      2250.0        200.0       2450.0
811    6357423   Wohnung       Einschlagstr. 15   Bolligen  3065     3.5         84.0      1390.0        290.0       1680.0
812    6357521   Wohnung    Einschlagstrasse 20   Bolligen  3065     3.5        114.0      1830.0        250.0       2080.0

In [194]:
#Bruttomiete 3.5-Zimmer in Bolligen:
dreieinhalbzimmer_bolligen.bruttomiete.median()

2035.0

In [195]:
#4.5-Zimmer-Wohnungen in Bolligen
viereinhalbzimmer_bolligen = df_bolligen[df_bolligen.zimmer == 4.5]
viereinhalbzimmer_bolligen.head(10)

objekt_id kategorie          objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
529    5721081   Wohnung       Rörswilstrasse 62   Bolligen  3065     4.5          NaN      1720.0        250.0       1970.0
549    6087299   Wohnung   Lutertalstrasse 49-55   Bolligen  3065     4.5        127.0      2190.0        350.0       2540.0
723    6263351   Wohnung         Lutertalstr. 62   Bolligen  3065     4.5        116.0      1450.0        380.0       1830.0
724    6263353   Wohnung         Lutertalstr. 60   Bolligen  3065     4.5        141.0      1730.0        440.0       2170.0
746    6317088   Wohnung  Flugbrunnenstrasse, 22   Bolligen  3065     4.5        109.0      1700.0        350.0       2050.0
819    6359588   Wohnung          Kirchstrasse 5   Bolligen  3065     4.5          NaN      1550.0        200.0       1750.0

In [196]:
#Durchschnittsmiete 4.5-Zimmer in Bolligen
viereinhalbzimmer_bolligen.bruttomiete.median()

2010.0

# 22. Ergebnisse für 3098 Köniz
Wie viele Wohnungen sind in Köniz total auf dem Markt (nach Immoscout)?

- 23 Wohnungen total, davon: 6 3.5-Zimmerwohnungen und 4 4.5-Zimmerwohnungen

Wie hoch ist die durchschnittliche Miete in Köniz für 3.5- und 4.5-Zimmerwohnung?

- 1510 Franken für eine 3.5-Z-Wohnung
- 1695 Franken für eine 4.5-Z-Wohnung

In [197]:
df_koeniz = df_immoscout[df_immoscout.objekt_ort == 'Köniz']
df_koeniz.head(10)

objekt_id kategorie            objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
181    6246084   Wohnung               Erikaweg 14      Köniz  3098     3.0         64.0      1430.0        220.0       1650.0
182    6248973   Wohnung              Sonnenweg 4a      Köniz  3098     3.5         70.0      1300.0        230.0       1530.0
194    6304281   Wohnung  Schwarzenburgstrasse 232      Köniz  3098     3.5         85.0      1300.0        270.0       1570.0
197    6307279   Wohnung              Sonnenweg 16      Köniz  3098     3.5         60.0         NaN          NaN       1450.0
211    6336521   Wohnung          Wiesenstrasse 24      Köniz  3098     2.5         60.0      1510.0        150.0       1660.0
214    6338829   Wohnung  Schwarzenburgstrasse 250      Köniz  3098     2.0          NaN      1100.0        150.0       1250.0
215    6338944   Wohnung          Wiesenstrasse 24      Köniz  3098     2.5          NaN      1600.0        150.0       1750.0
224    6348450   Wohnung              Fliederweg 8      Köniz  3098     3.0          NaN         NaN          NaN       1490.0
229    6352938   Wohnung             Tulpenweg 102      Köniz  3098     3.5         72.0      1380.0        460.0       1840.0
232    6354404   Wohnung           Wiesenstrasse 6      Köniz  3098     3.5         70.0      1250.0        210.0       1460.0

In [198]:
#Anzahl Wohnungen in Köniz
df_koeniz.shape

(23, 10)

In [200]:
#Nach Grösse
df_koeniz.zimmer.value_counts(ascending=False).head()

3.5    6
4.5    4
3.0    4
2.0    3
2.5    3
Name: zimmer, dtype: int64

In [201]:
#Anz Wohnungen in Köniz mit unbekannter Bruttomiete. Ergebenis: 0
df_koeniz[df_koeniz.bruttomiete.isnull()] 

Empty DataFrame
Columns: [objekt_id, kategorie, objekt_strasse, objekt_ort, plz, zimmer, nutzflaeche, nettomiete, nebenkosten, bruttomiete]
Index: []

In [202]:
#3.5-Zimmer-Wohnungen in Köniz
dreieinhalbzimmer_koeniz = df_koeniz[df_koeniz.zimmer == 3.5]
dreieinhalbzimmer_koeniz.head(10)

objekt_id kategorie            objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
182    6248973   Wohnung              Sonnenweg 4a      Köniz  3098     3.5         70.0      1300.0        230.0       1530.0
194    6304281   Wohnung  Schwarzenburgstrasse 232      Köniz  3098     3.5         85.0      1300.0        270.0       1570.0
197    6307279   Wohnung              Sonnenweg 16      Köniz  3098     3.5         60.0         NaN          NaN       1450.0
229    6352938   Wohnung             Tulpenweg 102      Köniz  3098     3.5         72.0      1380.0        460.0       1840.0
232    6354404   Wohnung           Wiesenstrasse 6      Köniz  3098     3.5         70.0      1250.0        210.0       1460.0
331    6258479   Wohnung  Schwarzenburgstrasse 342      Köniz  3098     3.5          NaN      1280.0        210.0       1490.0

In [203]:
#Durchschnittsmiete 3.5 Zimmer in Köniz:
dreieinhalbzimmer_koeniz.bruttomiete.median()

1510.0

In [204]:
#4.5-Zimmer-Wohnungen in Köniz
viereinhalbzimmer_koeniz = df_koeniz[df_koeniz.zimmer == 4.5]
viereinhalbzimmer_koeniz.head(10)

objekt_id kategorie      objekt_strasse objekt_ort   plz  zimmer  nutzflaeche  nettomiete  nebenkosten  bruttomiete
311    5759055   Wohnung  Köniztalstrasse 10      Köniz  3098     4.5         81.0      1430.0        265.0       1695.0
328    6224122   Wohnung  Talbodenstrasse 66      Köniz  3098     4.5        114.0      2270.0        340.0       2610.0
354    6337298   Wohnung   Köniztalstrasse 8      Köniz  3098     4.5         81.0      1450.0        245.0       1695.0
370    6361862   Wohnung  Dorfbachstrasse 56      Köniz  3098     4.5          NaN      1330.0        280.0       1610.0

In [205]:
#Durchschnittsmiete 4.5 ZImmer in Köniz:
viereinhalbzimmer_koeniz.bruttomiete.median()

1695.0